<?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?>
<!DOCTYPE mesh [
    <!ELEMENT mesh       (polygons)>
    <!ELEMENT polygons   (polygon+)>
    <!ELEMENT polygon    (vertex+)>
    <!ELEMENT vertex     (skin+)>
    <!ELEMENT skin        EMPTY>
    <!ATTLIST mesh texture CDATA #REQUIRED>
    <!ATTLIST vertex x CDATA #REQUIRED>
    <!ATTLIST vertex y CDATA #REQUIRED>
    <!ATTLIST vertex z CDATA #REQUIRED>
    <!ATTLIST vertex r CDATA #REQUIRED>
    <!ATTLIST vertex g CDATA #REQUIRED>
    <!ATTLIST vertex b CDATA #REQUIRED>
    <!ATTLIST vertex a CDATA #REQUIRED>
    <!ATTLIST vertex nx CDATA #REQUIRED>
    <!ATTLIST vertex ny CDATA #REQUIRED>
    <!ATTLIST vertex nz CDATA #REQUIRED>
    <!ATTLIST vertex u CDATA #REQUIRED>
    <!ATTLIST vertex v CDATA #REQUIRED>
    <!ATTLIST skin bone CDATA #REQUIRED>
    <!ATTLIST skin weight CDATA #REQUIRED>
]>
<mesh texture="native_peon">
    <polygons>
<polygon>
    <vertex x='15.434492111206055' y='0.31712862849235535' z='5.687793731689453'
            r='1' g='1' b='1' a='1'
            nx='-0.025924598798155785' ny='-0.13672886788845062' nz='0.9902691841125488'
            u='0.7740272283554077' v='0.3760504126548767'>
        <skin bone='dummy_bone' weight='1.0'/>
    </vertex>
    <vertex x='15.393590927124023' y='-0.31333473324775696' z='5.599673271179199'
            r='1' g='1' b='1' a='1'
            nx='-0.025924598798155785' ny='-0.13672886788845062' nz='0.9902691841125488'
            u='0.740807831287384' v='0.38137286901474'>
        <skin bone='dummy_bone' weight='1.0'/>
    </vertex>
    <vertex x='15.885140419006348' y='-0.30663803219795227' z='5.613466262817383'
            r='1' g='1' b='1' a='1'
            nx='-0.025924598798155785' ny='-0.13672886788845062' nz='0.9902691841125488'
            u='0.740807831287384' v='0.35845863819122314'>
        <skin bone='dummy_bone' weight='1.0'/>
    </vertex>
</polygon>
<polygon>
    <vertex x='15.434492111206055' y='0.31712862849235535' z='5.687793731689453'
            r='1' g='1' b='1' a='1'
            nx='0.2832459807395935' ny='0.09087153524160385' nz='0.9547325372695923'
            u='0.8737996816635132' v='0.4101351797580719'>
        <skin bone='dummy_bone' weight='1.0'/>
    </vertex>
    <vertex x='15.885140419006348' y='-0.30663803219795227' z='5.613466262817383'
            r='1' g='1' b='1' a='1'
            nx='0.2832459807395935' ny='0.09087153524160385' nz='0.9547325372695923'
            u='0.8737996816635132' v='0.4495035409927368'>
        <skin bone='dummy_bone' weight='1.0'/>
    </vertex>
    <vertex x='15.912413597106934' y='0.3231409192085266' z='5.545433044433594'
            r='1' g='1' b='1' a='1'
            nx='0.2832459807395935' ny='0.09087153524160385' nz='0.9547325372695923'
            u='0.8542386293411255' v='0.4221401512622833'>
        <skin bone='dummy_bone' weight='1.0'/>
    </vertex>
</polygon>
<polygon>
    <vertex x='15.912413597106934' y='0.3231409192085266' z='5.545433044433594'
            r='1' g='1' b='1' a='1'
            nx='0.9358348250389099' ny='-0.07766243070363998' nz='-0.3437758684158325'
            u='0.57268226146698' v='0.8540121912956238'>
        <skin bone='dummy_bone' weight='1.0'/>
    </vertex>
    <vertex x='15.885140419006348' y='-0.30663803219795227' z='5.613466262817383'
            r='1' g='1' b='1' a='1'
            nx='0.9358348250389099' ny='-0.07766243070363998' nz='-0.3437758684158325'
            u='0.57268226146698' v='0.8203901648521423'>
        <skin bone='dummy_bone' weight='1.0'/>
    </vertex>
    <vertex x='15.705183029174805' y='-0.31063902378082275' z='5.124486923217773'
            r='1' g='1' b='1' a='1'
            nx='0.9358348250389099' ny='-0.07766243070363998' nz='-0.3437758684158325'
            u='0.5952439904212952' v='0.8216840624809265'>
        <skin bone='dummy_bone' weight='1.0'/>
    </vertex>
</polygon>
<polygon>
    <vertex x='15.912413597106934' y='0.3231409192085266' z='5.545433044433594'
            r='1' g='1' b='1' a='1'
            nx='0.9241945147514343' ny='-0.050775863230228424' nz='-0.3785318434238434'
            u='0.57268226146698' v='0.8540121912956238'>
        <skin bone='dummy_bone' weight='1.0'/>
    </vertex>
    <vertex x='15.705183029174805' y='-0.31063902378082275' z='5.124486923217773'
            r='1' g='1' b='1' a='1'
            nx='0.9241945147514343' ny='-0.050775863230228424' nz='-0.3785318434238434'
            u='0.5952439904212952' v='0.8216840624809265'>
        <skin bone='dummy_bone' weight='1.0'/>
    </vertex>
    <vertex x='15.717019081115723' y='0.3189709782600403' z='5.068932056427002'
            r='1' g='1' b='1' a='1'
            nx='0.9241945147514343' ny='-0.050775863230228424' nz='-0.3785318434238434'
            u='0.5955458283424377' v='0.8552457690238953'>
        <skin bone='dummy_bone' weight='1.0'/>
    </vertex>
</polygon>
<polygon>
    <vertex x='15.717019081115723' y='0.3189709782600403' z='5.068932056427002'
            r='1' g='1' b='1' a='1'
            nx='-0.38161700963974' ny='-0.07412339746952057' nz='-0.9213436841964722'
            u='0.26196610927581787' v='0.8716669082641602'>
        <skin bone='dummy_bone' weight='1.0'/>
    </vertex>
    <vertex x='15.705183029174805' y='-0.31063902378082275' z='5.124486923217773'
            r='1' g='1' b='1' a='1'
            nx='-0.38161700963974' ny='-0.07412339746952057' nz='-0.9213436841964722'
            u='0.2630269229412079' v='0.8381817936897278'>
        <skin bone='dummy_bone' weight='1.0'/>
    </vertex>
    <vertex x='15.273033142089844' y='0.31355226039886475' z='5.253264427185059'
            r='1' g='1' b='1' a='1'
            nx='-0.38161700963974' ny='-0.07412339746952057' nz='-0.9213436841964722'
            u='0.2832997441291809' v='0.8716669082641602'>
        <skin bone='dummy_bone' weight='1.0'/>
    </vertex>
</polygon>
<polygon>
    <vertex x='15.273033142089844' y='0.31355226039886475' z='5.253264427185059'
            r='1' g='1' b='1' a='1'
            nx='-0.34816882014274597' ny='-0.04789899289608002' nz='-0.9362072944641113'
            u='0.2832997441291809' v='0.8716669082641602'>
        <skin bone='dummy_bone' weight='1.0'/>
    </vertex>
    <vertex x='15.705183029174805' y='-0.31063902378082275' z='5.124486923217773'
            r='1' g='1' b='1' a='1'
            nx='-0.34816882014274597' ny='-0.04789899289608002' nz='-0.9362072944641113'
            u='0.2630269229412079' v='0.8381817936897278'>
        <skin bone='dummy_bone' weight='1.0'/>
    </vertex>
    <vertex x='15.280062675476074' y='-0.3158855736255646' z='5.2828545570373535'
            r='1' g='1' b='1' a='1'
            nx='-0.34816882014274597' ny='-0.04789899289608002' nz='-0.9362072944641113'
            u='0.28265953063964844' v='0.8382734060287476'>
        <skin bone='dummy_bone' weight='1.0'/>
    </vertex>
</polygon>
<polygon>
    <vertex x='15.273033142089844' y='0.31355226039886475' z='5.253264427185059'
            r='1' g='1' b='1' a='1'
            nx='-0.9413847327232361' ny='0.0053463466465473175' nz='0.33729222416877747'
            u='0.7749426960945129' v='0.39508551359176636'>
        <skin bone='dummy_bone' weight='1.0'/>
    </vertex>
    <vertex x='15.280062675476074' y='-0.3158855736255646' z='5.2828545570373535'
            r='1' g='1' b='1' a='1'
            nx='-0.9413847327232361' ny='0.0053463466465473175' nz='0.33729222416877747'
            u='0.7414755821228027' v='0.3950593173503876'>
        <skin bone='dummy_bone' weight='1.0'/>
    </vertex>
    <vertex x='15.393590927124023' y='-0.31333473324775696' z='5.599673271179199'
            r='1' g='1' b='1' a='1'
            nx='-0.9413847327232361' ny='0.0053463466465473175' nz='0.33729222416877747'
            u='0.740807831287384' v='0.38137286901474'>
        <skin bone='dummy_bone' weight='1.0'/>
    </vertex>
</polygon>
<polygon>
    <vertex x='15.273033142089844' y='0.31355226039886475' z='5.253264427185059'
            r='1' g='1' b='1' a='1'
            nx='-0.937345027923584' ny='0.012143433094024658' nz='0.34819069504737854'
            u='0.7749426960945129' v='0.39508551359176636'>
        <skin bone='dummy_bone' weight='1.0'/>
    </vertex>
    <vertex x='15.393590927124023' y='-0.31333473324775696' z='5.599673271179199'
            r='1' g='1' b='1' a='1'
            nx='-0.937345027923584' ny='0.012143433094024658' nz='0.34819069504737854'
            u='0.740807831287384' v='0.38137286901474'>
        <skin bone='dummy_bone' weight='1.0'/>
    </vertex>
    <vertex x='15.434492111206055' y='0.31712862849235535' z='5.687793731689453'
            r='1' g='1' b='1' a='1'
            nx='-0.937345027923584' ny='0.012143433094024658' nz='0.34819069504737854'
            u='0.7740272283554077' v='0.3760504126548767'>
        <skin bone='dummy_bone' weight='1.0'/>
    </vertex>
</polygon>
<polygon>
    <vertex x='15.393590927124023' y='-0.31333473324775696' z='5.599673271179199'
            r='1' g='1' b='1' a='1'
            nx='0.013532648794353008' ny='-0.9999033212661743' nz='0.003201174782589078'
            u='0.4328605532646179' v='0.7775834798812866'>
        <skin bone='dummy_bone' weight='1.0'/>
    </vertex>
    <vertex x='15.280062675476074' y='-0.3158855736255646' z='5.2828545570373535'
            r='1' g='1' b='1' a='1'
            nx='0.013532648794353008' ny='-0.9999033212661743' nz='0.003201174782589078'
            u='0.44595593214035034' v='0.7885395288467407'>
        <skin bone='dummy_bone' weight='1.0'/>
    </vertex>
    <vertex x='15.705183029174805' y='-0.31063902378082275' z='5.124486923217773'
            r='1' g='1' b='1' a='1'
            nx='0.013532648794353008' ny='-0.9999033212661743' nz='0.003201174782589078'
            u='0.4328605532646179' v='0.8077431917190552'>
        <skin bone='dummy_bone' weight='1.0'/>
    </vertex>
</polygon>
<polygon>
    <vertex x='15.714786529541016' y='-0.30913373827934265' z='5.554055213928223'
            r='1' g='1' b='1' a='1'
            nx='0.013532216660678387' ny='-0.9999032616615295' nz='0.003201239975169301'
            u='0.49726855754852295' v='0.8510173559188843'>
        <skin bone='dummy_bone' weight='1.0'/>
    </vertex>
    <vertex x='15.705183029174805' y='-0.31063902378082275' z='5.124486923217773'
            r='1' g='1' b='1' a='1'
            nx='0.013532216660678387' ny='-0.9999032616615295' nz='0.003201239975169301'
            u='0.4967927932739258' v='0.8733885288238525'>
        <skin bone='dummy_bone' weight='1.0'/>
    </vertex>
    <vertex x='15.885140419006348' y='-0.30663803219795227' z='5.613466262817383'
            r='1' g='1' b='1' a='1'
            nx='0.013532216660678387' ny='-0.9999032616615295' nz='0.003201239975169301'
            u='0.4889325797557831' v='0.8481704592704773'>
        <skin bone='dummy_bone' weight='1.0'/>
    </vertex>
</polygon>
<polygon>
    <vertex x='15.714786529541016' y='-0.30913373827934265' z='5.554055213928223'
            r='1' g='1' b='1' a='1'
            nx='0.013532443903386593' ny='-0.9999033212661743' nz='0.003201467916369438'
            u='0.49726855754852295' v='0.8510173559188843'>
        <skin bone='dummy_bone' weight='1.0'/>
    </vertex>
    <vertex x='15.885140419006348' y='-0.30663803219795227' z='5.613466262817383'
            r='1' g='1' b='1' a='1'
            nx='0.013532443903386593' ny='-0.9999033212661743' nz='0.003201467916369438'
            u='0.4889325797557831' v='0.8481704592704773'>
        <skin bone='dummy_bone' weight='1.0'/>
    </vertex>
    <vertex x='15.393590927124023' y='-0.31333473324775696' z='5.599673271179199'
            r='1' g='1' b='1' a='1'
            nx='0.013532443903386593' ny='-0.9999033212661743' nz='0.003201467916369438'
            u='0.5133354663848877' v='0.8481704592704773'>
        <skin bone='dummy_bone' weight='1.0'/>
    </vertex>
</polygon>
<polygon>
    <vertex x='15.714786529541016' y='-0.30913373827934265' z='5.554055213928223'
            r='1' g='1' b='1' a='1'
            nx='-0.5501700043678284' ny='-0.18743665516376495' nz='-0.8137447237968445'
            u='0.8542386293411255' v='0.48400044441223145'>
        <skin bone='dummy_bone' weight='1.0'/>
    </vertex>
    <vertex x='15.512971878051758' y='0.3177371621131897' z='5.546109199523926'
            r='1' g='1' b='1' a='1'
            nx='-0.5501700043678284' ny='-0.18743665516376495' nz='-0.8137447237968445'
            u='0.8542386293411255' v='0.44950351119041443'>
        <skin bone='dummy_bone' weight='1.0'/>
    </vertex>
    <vertex x='15.784404754638672' y='0.3208208680152893' z='5.361884593963623'
            r='1' g='1' b='1' a='1'
            nx='-0.5501700043678284' ny='-0.18743665516376495' nz='-0.8137447237968445'
            u='0.8701160550117493' v='0.4526226222515106'>
        <skin bone='dummy_bone' weight='1.0'/>
    </vertex>
</polygon>
<polygon>
    <vertex x='15.714786529541016' y='-0.30913373827934265' z='5.554055213928223'
            r='1' g='1' b='1' a='1'
            nx='-0.992965042591095' ny='0.11638472229242325' nz='0.021791135892271996'
            u='0.8542386293411255' v='0.48400044441223145'>
        <skin bone='dummy_bone' weight='1.0'/>
    </vertex>
    <vertex x='15.784404754638672' y='0.3208208680152893' z='5.361884593963623'
            r='1' g='1' b='1' a='1'
            nx='-0.992965042591095' ny='0.11638472229242325' nz='0.021791135892271996'
            u='0.8701160550117493' v='0.4526226222515106'>
        <skin bone='dummy_bone' weight='1.0'/>
    </vertex>
    <vertex x='15.705183029174805' y='-0.31063902378082275' z='5.124486923217773'
            r='1' g='1' b='1' a='1'
            nx='-0.992965042591095' ny='0.11638472229242325' nz='0.021791135892271996'
            u='0.8728131055831909' v='0.48583871126174927'>
        <skin bone='dummy_bone' weight='1.0'/>
    </vertex>
</polygon>
<polygon>
    <vertex x='15.705183029174805' y='-0.31063902378082275' z='5.124486923217773'
            r='1' g='1' b='1' a='1'
            nx='-0.26693055033683777' ny='-0.30961307883262634' nz='0.9126269221305847'
            u='0.8243193626403809' v='0.827117919921875'>
        <skin bone='dummy_bone' weight='1.0'/>
    </vertex>
    <vertex x='15.784404754638672' y='0.3208208680152893' z='5.361884593963623'
            r='1' g='1' b='1' a='1'
            nx='-0.26693055033683777' ny='-0.30961307883262634' nz='0.9126269221305847'
            u='0.8350436091423035' v='0.8601379990577698'>
        <skin bone='dummy_bone' weight='1.0'/>
    </vertex>
    <vertex x='15.4607515335083' y='0.31613239645957947' z='5.265629768371582'
            r='1' g='1' b='1' a='1'
            nx='-0.26693055033683777' ny='-0.30961307883262634' nz='0.9126269221305847'
            u='0.8176220059394836' v='0.8601379990577698'>
        <skin bone='dummy_bone' weight='1.0'/>
    </vertex>
</polygon>
<polygon>
    <vertex x='15.705183029174805' y='-0.31063902378082275' z='5.124486923217773'
            r='1' g='1' b='1' a='1'
            nx='0.819135844707489' ny='0.19824062287807465' nz='0.5382537245750427'
            u='0.8176219463348389' v='0.8271180391311646'>
        <skin bone='dummy_bone' weight='1.0'/>
    </vertex>
    <vertex x='15.4607515335083' y='0.31613239645957947' z='5.265629768371582'
            r='1' g='1' b='1' a='1'
            nx='0.819135844707489' ny='0.19824062287807465' nz='0.5382537245750427'
            u='0.8039556741714478' v='0.8609452247619629'>
        <skin bone='dummy_bone' weight='1.0'/>
    </vertex>
    <vertex x='15.393590927124023' y='-0.31333473324775696' z='5.599673271179199'
            r='1' g='1' b='1' a='1'
            nx='0.819135844707489' ny='0.19824062287807465' nz='0.5382537245750427'
            u='0.7879103422164917' v='0.8271180391311646'>
        <skin bone='dummy_bone' weight='1.0'/>
    </vertex>
</polygon>
<polygon>
    <vertex x='15.393590927124023' y='-0.31333473324775696' z='5.599673271179199'
            r='1' g='1' b='1' a='1'
            nx='0.9639473557472229' ny='-0.1974859982728958' nz='-0.1783396452665329'
            u='0.4459557831287384' v='0.7425107955932617'>
        <skin bone='dummy_bone' weight='1.0'/>
    </vertex>
    <vertex x='15.4607515335083' y='0.31613239645957947' z='5.265629768371582'
            r='1' g='1' b='1' a='1'
            nx='0.9639473557472229' ny='-0.1974859982728958' nz='-0.1783396452665329'
            u='0.4459557831287384' v='0.7775834202766418'>
        <skin bone='dummy_bone' weight='1.0'/>
    </vertex>
    <vertex x='15.512971878051758' y='0.3177371621131897' z='5.546109199523926'
            r='1' g='1' b='1' a='1'
            nx='0.9639473557472229' ny='-0.1974859982728958' nz='-0.1783396452665329'
            u='0.43556392192840576' v='0.7748807072639465'>
        <skin bone='dummy_bone' weight='1.0'/>
    </vertex>
</polygon>
<polygon>
    <vertex x='15.393590927124023' y='-0.31333473324775696' z='5.599673271179199'
            r='1' g='1' b='1' a='1'
            nx='-0.13964852690696716' ny='-0.0574876107275486' nz='-0.9885309338569641'
            u='0.4459557831287384' v='0.7425107955932617'>
        <skin bone='dummy_bone' weight='1.0'/>
    </vertex>
    <vertex x='15.512971878051758' y='0.3177371621131897' z='5.546109199523926'
            r='1' g='1' b='1' a='1'
            nx='-0.13964852690696716' ny='-0.0574876107275486' nz='-0.9885309338569641'
            u='0.43556392192840576' v='0.7748807072639465'>
        <skin bone='dummy_bone' weight='1.0'/>
    </vertex>
    <vertex x='15.714786529541016' y='-0.30913373827934265' z='5.554055213928223'
            r='1' g='1' b='1' a='1'
            nx='-0.13964852690696716' ny='-0.0574876107275486' nz='-0.9885309338569641'
            u='0.43335169553756714' v='0.7408236265182495'>
        <skin bone='dummy_bone' weight='1.0'/>
    </vertex>
</polygon>
<polygon>
    <vertex x='15.4607515335083' y='0.31613239645957947' z='5.265629768371582'
            r='1' g='1' b='1' a='1'
            nx='-0.013532635755836964' ny='0.9999032616615295' nz='-0.0032014241442084312'
            u='0.7392002940177917' v='0.860872209072113'>
        <skin bone='dummy_bone' weight='1.0'/>
    </vertex>
    <vertex x='15.273033142089844' y='0.31355226039886475' z='5.253264427185059'
            r='1' g='1' b='1' a='1'
            nx='-0.013532635755836964' ny='0.9999032616615295' nz='-0.0032014241442084312'
            u='0.7302256226539612' v='0.8652644157409668'>
        <skin bone='dummy_bone' weight='1.0'/>
    </vertex>
    <vertex x='15.512971878051758' y='0.3177371621131897' z='5.546109199523926'
            r='1' g='1' b='1' a='1'
            nx='-0.013532635755836964' ny='0.9999032616615295' nz='-0.0032014241442084312'
            u='0.7361148595809937' v='0.8460400104522705'>
        <skin bone='dummy_bone' weight='1.0'/>
    </vertex>
</polygon>
<polygon>
    <vertex x='15.512971878051758' y='0.3177371621131897' z='5.546109199523926'
            r='1' g='1' b='1' a='1'
            nx='-0.013532677665352821' ny='0.9999032616615295' nz='-0.003201395273208618'
            u='0.7361148595809937' v='0.8460400104522705'>
        <skin bone='dummy_bone' weight='1.0'/>
    </vertex>
    <vertex x='15.273033142089844' y='0.31355226039886475' z='5.253264427185059'
            r='1' g='1' b='1' a='1'
            nx='-0.013532677665352821' ny='0.9999032616615295' nz='-0.003201395273208618'
            u='0.7302256226539612' v='0.8652644157409668'>
        <skin bone='dummy_bone' weight='1.0'/>
    </vertex>
    <vertex x='15.434492111206055' y='0.31712862849235535' z='5.687793731689453'
            r='1' g='1' b='1' a='1'
            nx='-0.013532677665352821' ny='0.9999032616615295' nz='-0.003201395273208618'
            u='0.7294037342071533' v='0.8406615853309631'>
        <skin bone='dummy_bone' weight='1.0'/>
    </vertex>
</polygon>
<polygon>
    <vertex x='15.784404754638672' y='0.3208208680152893' z='5.361884593963623'
            r='1' g='1' b='1' a='1'
            nx='-0.013532549142837524' ny='0.9999033212661743' nz='-0.0032011116854846478'
            u='0.7531640529632568' v='0.8496180772781372'>
        <skin bone='dummy_bone' weight='1.0'/>
    </vertex>
    <vertex x='15.717019081115723' y='0.3189709782600403' z='5.068932056427002'
            r='1' g='1' b='1' a='1'
            nx='-0.013532549142837524' ny='0.9999033212661743' nz='-0.0032011116854846478'
            u='0.7557556629180908' v='0.8653688430786133'>
        <skin bone='dummy_bone' weight='1.0'/>
    </vertex>
    <vertex x='15.4607515335083' y='0.31613239645957947' z='5.265629768371582'
            r='1' g='1' b='1' a='1'
            nx='-0.013532549142837524' ny='0.9999033212661743' nz='-0.0032011116854846478'
            u='0.7392002940177917' v='0.860872209072113'>
        <skin bone='dummy_bone' weight='1.0'/>
    </vertex>
</polygon>
<polygon>
    <vertex x='15.4607515335083' y='0.31613239645957947' z='5.265629768371582'
            r='1' g='1' b='1' a='1'
            nx='-0.01353233028203249' ny='0.9999033212661743' nz='-0.003201216459274292'
            u='0.7392002940177917' v='0.860872209072113'>
        <skin bone='dummy_bone' weight='1.0'/>
    </vertex>
    <vertex x='15.717019081115723' y='0.3189709782600403' z='5.068932056427002'
            r='1' g='1' b='1' a='1'
            nx='-0.01353233028203249' ny='0.9999033212661743' nz='-0.003201216459274292'
            u='0.7557556629180908' v='0.8653688430786133'>
        <skin bone='dummy_bone' weight='1.0'/>
    </vertex>
    <vertex x='15.273033142089844' y='0.31355226039886475' z='5.253264427185059'
            r='1' g='1' b='1' a='1'
            nx='-0.01353233028203249' ny='0.9999033212661743' nz='-0.003201216459274292'
            u='0.7302256226539612' v='0.8652644157409668'>
        <skin bone='dummy_bone' weight='1.0'/>
    </vertex>
</polygon>
<polygon>
    <vertex x='15.784404754638672' y='0.3208208680152893' z='5.361884593963623'
            r='1' g='1' b='1' a='1'
            nx='-0.013532047159969807' ny='0.9999033212661743' nz='-0.0032014132011681795'
            u='0.7531640529632568' v='0.8496180772781372'>
        <skin bone='dummy_bone' weight='1.0'/>
    </vertex>
    <vertex x='15.912413597106934' y='0.3231409192085266' z='5.545433044433594'
            r='1' g='1' b='1' a='1'
            nx='-0.013532047159969807' ny='0.9999033212661743' nz='-0.0032014132011681795'
            u='0.7557556629180908' v='0.8380197882652283'>
        <skin bone='dummy_bone' weight='1.0'/>
    </vertex>
    <vertex x='15.717019081115723' y='0.3189709782600403' z='5.068932056427002'
            r='1' g='1' b='1' a='1'
            nx='-0.013532047159969807' ny='0.9999033212661743' nz='-0.0032014132011681795'
            u='0.7557556629180908' v='0.8653688430786133'>
        <skin bone='dummy_bone' weight='1.0'/>
    </vertex>
</polygon>
<polygon>
    <vertex x='15.512971878051758' y='0.3177371621131897' z='5.546109199523926'
            r='1' g='1' b='1' a='1'
            nx='-0.013532468117773533' ny='0.9999032616615295' nz='-0.0032006963156163692'
            u='0.7361148595809937' v='0.8460400104522705'>
        <skin bone='dummy_bone' weight='1.0'/>
    </vertex>
    <vertex x='15.434492111206055' y='0.31712862849235535' z='5.687793731689453'
            r='1' g='1' b='1' a='1'
            nx='-0.013532468117773533' ny='0.9999032616615295' nz='-0.0032006963156163692'
            u='0.7294037342071533' v='0.8406615853309631'>
        <skin bone='dummy_bone' weight='1.0'/>
    </vertex>
    <vertex x='15.912413597106934' y='0.3231409192085266' z='5.545433044433594'
            r='1' g='1' b='1' a='1'
            nx='-0.013532468117773533' ny='0.9999032616615295' nz='-0.0032006963156163692'
            u='0.7557556629180908' v='0.8380197882652283'>
        <skin bone='dummy_bone' weight='1.0'/>
    </vertex>
</polygon>
<polygon>
    <vertex x='15.512971878051758' y='0.3177371621131897' z='5.546109199523926'
            r='1' g='1' b='1' a='1'
            nx='-0.013532446697354317' ny='0.9999032616615295' nz='-0.0032012632582336664'
            u='0.7361148595809937' v='0.8460400104522705'>
        <skin bone='dummy_bone' weight='1.0'/>
    </vertex>
    <vertex x='15.912413597106934' y='0.3231409192085266' z='5.545433044433594'
            r='1' g='1' b='1' a='1'
            nx='-0.013532446697354317' ny='0.9999032616615295' nz='-0.0032012632582336664'
            u='0.7557556629180908' v='0.8380197882652283'>
        <skin bone='dummy_bone' weight='1.0'/>
    </vertex>
    <vertex x='15.784404754638672' y='0.3208208680152893' z='5.361884593963623'
            r='1' g='1' b='1' a='1'
            nx='-0.013532446697354317' ny='0.9999032616615295' nz='-0.0032012632582336664'
            u='0.7531640529632568' v='0.8496180772781372'>
        <skin bone='dummy_bone' weight='1.0'/>
    </vertex>
</polygon>
<polygon>
    <vertex x='11.561131477355957' y='-0.2378300577402115' z='1.6784472465515137'
            r='1' g='1' b='1' a='1'
            nx='0.013532550074160099' ny='-0.9999033212661743' nz='0.003201244166120887'
            u='0.7474033832550049' v='0.4864669144153595'>
        <skin bone='dummy_bone' weight='1.0'/>
    </vertex>
    <vertex x='12.554740905761719' y='-0.22424760460853577' z='1.7206401824951172'
            r='1' g='1' b='1' a='1'
            nx='0.013532550074160099' ny='-0.9999033212661743' nz='0.003201244166120887'
            u='0.7394149899482727' v='0.437816858291626'>
        <skin bone='dummy_bone' weight='1.0'/>
    </vertex>
    <vertex x='12.547977447509766' y='-0.22337718307971954' z='2.0211145877838135'
            r='1' g='1' b='1' a='1'
            nx='0.013532550074160099' ny='-0.9999033212661743' nz='0.003201244166120887'
            u='0.755013108253479' v='0.43603163957595825'>
        <skin bone='dummy_bone' weight='1.0'/>
    </vertex>
</polygon>
<polygon>
    <vertex x='12.547977447509766' y='-0.22337718307971954' z='2.0211145877838135'
            r='1' g='1' b='1' a='1'
            nx='0.9996554255485535' ny='0.013585405424237251' nz='0.022461963817477226'
            u='0.8609405755996704' v='0.26651689410209656'>
        <skin bone='dummy_bone' weight='1.0'/>
    </vertex>
    <vertex x='12.554978370666504' y='-0.2417570799589157' z='1.7206964492797852'
            r='1' g='1' b='1' a='1'
            nx='0.9996554255485535' ny='0.013585405424237251' nz='0.022461963817477226'
            u='0.8511478304862976' v='0.27318257093429565'>
        <skin bone='dummy_bone' weight='1.0'/>
    </vertex>
    <vertex x='12.554740905761719' y='-0.22424760460853577' z='1.7206401824951172'
            r='1' g='1' b='1' a='1'
            nx='0.9996554255485535' ny='0.013585405424237251' nz='0.022461963817477226'
            u='0.8506326675415039' v='0.27241167426109314'>
        <skin bone='dummy_bone' weight='1.0'/>
    </vertex>
</polygon>
<polygon>
    <vertex x='12.396635055541992' y='-0.01794004999101162' z='0.9984739422798157'
            r='1' g='1' b='1' a='1'
            nx='0.008886771276593208' ny='-0.9545941352844238' nz='-0.29777684807777405'
            u='0.703964114189148' v='0.4101351201534271'>
        <skin bone='dummy_bone' weight='1.0'/>
    </vertex>
    <vertex x='12.554978370666504' y='-0.2417570799589157' z='1.7206964492797852'
            r='1' g='1' b='1' a='1'
            nx='0.008886771276593208' ny='-0.9545941352844238' nz='-0.29777684807777405'
            u='0.7392978072166443' v='0.4381684958934784'>
        <skin bone='dummy_bone' weight='1.0'/>
    </vertex>
    <vertex x='11.561131477355957' y='-0.2378300577402115' z='1.6784472465515137'
            r='1' g='1' b='1' a='1'
            nx='0.008886771276593208' ny='-0.9545941352844238' nz='-0.29777684807777405'
            u='0.7474033832550049' v='0.4864669144153595'>
        <skin bone='dummy_bone' weight='1.0'/>
    </vertex>
</polygon>
<polygon>
    <vertex x='11.561131477355957' y='-0.2378300577402115' z='1.6784472465515137'
            r='1' g='1' b='1' a='1'
            nx='0.013532472774386406' ny='-0.9999033212661743' nz='0.0032013379968702793'
            u='0.7474033832550049' v='0.4864669144153595'>
        <skin bone='dummy_bone' weight='1.0'/>
    </vertex>
    <vertex x='12.547977447509766' y='-0.22337718307971954' z='2.0211145877838135'
            r='1' g='1' b='1' a='1'
            nx='0.013532472774386406' ny='-0.9999033212661743' nz='0.0032013379968702793'
            u='0.755013108253479' v='0.43603163957595825'>
        <skin bone='dummy_bone' weight='1.0'/>
    </vertex>
    <vertex x='12.632518768310547' y='-0.2213229089975357' z='2.3053719997406006'
            r='1' g='1' b='1' a='1'
            nx='0.013532472774386406' ny='-0.9999033212661743' nz='0.0032013379968702793'
            u='0.7688387036323547' v='0.42991724610328674'>
        <skin bone='dummy_bone' weight='1.0'/>
    </vertex>
</polygon>
<polygon>
    <vertex x='11.561131477355957' y='-0.2378300577402115' z='1.6784472465515137'
            r='1' g='1' b='1' a='1'
            nx='0.013532663695514202' ny='-0.9999032616615295' nz='0.0032013587187975645'
            u='0.7474033832550049' v='0.4864669144153595'>
        <skin bone='dummy_bone' weight='1.0'/>
    </vertex>
    <vertex x='12.632518768310547' y='-0.2213229089975357' z='2.3053719997406006'
            r='1' g='1' b='1' a='1'
            nx='0.013532663695514202' ny='-0.9999032616615295' nz='0.0032013587187975645'
            u='0.7688387036323547' v='0.42991724610328674'>
        <skin bone='dummy_bone' weight='1.0'/>
    </vertex>
    <vertex x='12.688013076782227' y='-0.21972353756427765' z='2.5703394412994385'
            r='1' g='1' b='1' a='1'
            nx='0.013532663695514202' ny='-0.9999032616615295' nz='0.0032013587187975645'
            u='0.7819646596908569' v='0.42535215616226196'>
        <skin bone='dummy_bone' weight='1.0'/>
    </vertex>
</polygon>
<polygon>
    <vertex x='11.561131477355957' y='-0.2378300577402115' z='1.6784472465515137'
            r='1' g='1' b='1' a='1'