<?xml version="1.0" encoding="UTF-8" standalone="yes"?>

<!DOCTYPE animation [
	<!ELEMENT animation  (frame+)>
	<!ELEMENT frame      (transform+)>
	<!ELEMENT transform   EMPTY>
	<!ATTLIST frame index CDATA #REQUIRED>
	<!ATTLIST transform name CDATA #REQUIRED>
	<!ATTLIST transform m00 CDATA #REQUIRED>
	<!ATTLIST transform m01 CDATA #REQUIRED>
	<!ATTLIST transform m02 CDATA #REQUIRED>
	<!ATTLIST transform m03 CDATA #REQUIRED>
	<!ATTLIST transform m10 CDATA #REQUIRED>
	<!ATTLIST transform m11 CDATA #REQUIRED>
	<!ATTLIST transform m12 CDATA #REQUIRED>
	<!ATTLIST transform m13 CDATA #REQUIRED>
	<!ATTLIST transform m20 CDATA #REQUIRED>
	<!ATTLIST transform m21 CDATA #REQUIRED>
	<!ATTLIST transform m22 CDATA #REQUIRED>
	<!ATTLIST transform m23 CDATA #REQUIRED>
	<!ATTLIST transform m30 CDATA #REQUIRED>
	<!ATTLIST transform m31 CDATA #REQUIRED>
	<!ATTLIST transform m32 CDATA #REQUIRED>
	<!ATTLIST transform m33 CDATA #REQUIRED>
]>

<animation>
	<frame index="0">
		<transform name="peon bip Pelvis"
			m00="-0.000158119" m10="0.956068" m20="0.293144" m30="-0.0226135"
			m01="-0.0214029" m11="-0.293081" m21="0.955848" m31="0.00133583"
			m02="0.999771" m12="-0.00612299" m22="0.0205089" m32="0.3924"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip Spine"
			m00="0.144024" m10="0.96136" m20="0.234613" m30="-0.0493026"
			m01="0.0255145" m11="-0.240613" m21="0.970285" m31="-0.00350136"
			m02="0.989245" m12="-0.133759" m22="-0.0591828" m32="0.568708"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip L Thigh"
			m00="0.267299" m10="0.94816" m20="-0.17188" m30="0.0206892"
			m01="-0.173668" m11="-0.128048" m21="-0.976444" m31="0.142531"
			m02="-0.947835" m12="0.290853" m22="0.130438" m32="0.39543"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip R Thigh"
			m00="0.681968" m10="0.688981" m20="-0.245407" m30="-0.0659162"
			m01="-0.0455767" m11="-0.294853" m21="-0.954455" m31="-0.139859"
			m02="-0.72996" m12="0.662093" m22="-0.169679" m32="0.389371"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip L Toe0"
			m00="0.981547" m10="-4.51776e-006" m20="0.19122" m30="0.0921541"
			m01="0.19122" m11="-0.000548913" m21="-0.981547" m31="0.137063"
			m02="0.00010939" m12="1.0" m22="-0.000537912" m32="0.00526446"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip L Foot"
			m00="4.57627e-006" m10="0.981547" m20="0.19122" m30="-0.0248488"
			m01="0.000548924" m11="0.19122" m21="-0.981547" m31="0.114204"
			m02="-1.0" m12="0.000109449" m22="-0.000537912" m32="0.12337"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip Spine2"
			m00="0.488892" m10="0.844349" m20="0.219224" m30="0.0186845"
			m01="-0.232443" m11="-0.116131" m21="0.965652" m31="0.00340926"
			m02="0.840806" m12="-0.523057" m22="0.139487" m32="0.89338"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip Spine1"
			m00="0.266517" m10="0.947087" m20="0.178873" m30="-0.0254922"
			m01="0.0158197" m11="-0.189859" m21="0.981684" m31="0.000764095"
			m02="0.9637" m12="-0.258806" m22="-0.0655834" m32="0.733148"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip R Clavicle"
			m00="-0.219222" m10="-0.844738" m20="-0.488219" m30="0.101769"
			m01="-0.965652" m11="0.116313" m21="0.23235" m31="-0.0442067"
			m02="-0.139489" m12="0.522387" m22="-0.841222" m32="1.03807"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip R UpperArm"
			m00="-0.186708" m10="-0.901053" m20="-0.391464" m30="0.0894062"
			m01="-0.7237" m11="-0.143325" m21="0.675067" m31="-0.0986624"
			m02="-0.664378" m12="0.409343" m22="-0.625332" m32="1.03021"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip Neck"
			m00="0.532247" m10="0.817712" m20="0.219224" m30="0.103367"
			m01="-0.238181" m11="-0.103855" m21="0.965652" m31="-0.0368752"
			m02="0.812393" m12="-0.566181" m22="0.139487" m32="1.03917"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip Head"
			m00="0.12071" m10="0.95063" m20="0.285889" m30="0.1558"
			m01="0.0866681" m11="-0.296987" m21="0.95094" m31="-0.0603389"
			m02="0.988897" m12="-0.0900104" m22="-0.118239" m32="1.1192"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip R Forearm"
			m00="0.16977" m10="-0.904397" m20="-0.391464" m30="0.0508909"
			m01="-0.614916" m11="-0.407629" m21="0.675067" m31="-0.247952"
			m02="-0.770101" m12="0.126111" m22="-0.625332" m32="0.893153"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip R Hand"
			m00="0.128971" m10="0.861123" m20="0.491765" m30="0.0880159"
			m01="-0.639759" m11="0.451155" m21="-0.622228" m31="-0.382421"
			m02="-0.757677" m12="-0.234362" m22="0.609098" m32="0.724749"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip R Calf"
			m00="-0.536733" m10="0.807275" m20="-0.245407" m30="0.0784879"
			m01="0.279531" m11="-0.104297" m21="-0.954455" m31="-0.14951"
			m02="-0.796103" m12="-0.580887" m22="-0.169679" m32="0.234805"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip R Foot"
			m00="0.109086" m10="0.834899" m20="-0.539484" m30="0.0114595"
			m01="-0.0791601" m11="-0.533703" m21="-0.841959" m31="-0.114602"
			m02="-0.990875" m12="0.134552" m22="0.00787125" m32="0.135386"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip R Toe0"
			m00="0.834899" m10="-0.109086" m20="-0.539484" m30="0.123866"
			m01="-0.533703" m11="0.0791601" m21="-0.841959" m31="-0.18757"
			m02="0.134552" m12="0.990875" m22="0.00787125" m32="0.0343836"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip L UpperArm"
			m00="0.124299" m10="-0.648846" m20="0.750699" m30="0.117456"
			m01="0.647738" m11="0.626182" m21="0.433972" m31="0.0248956"
			m02="-0.751655" m12="0.432314" m22="0.498116" m32="1.04805"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip L Clavicle"
			m00="0.219222" m10="-0.844738" m20="0.48822" m30="0.105094"
			m01="0.965652" m11="0.116313" m21="-0.23235" m31="-0.0295601"
			m02="0.139488" m12="0.522387" m22="0.841222" m32="1.04019"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip L Forearm"
			m00="0.44153" m10="-0.491428" m20="0.750699" m30="0.143097"
			m01="0.231287" m11="0.870732" m21="0.433972" m31="0.158515"
			m02="-0.866924" m12="-0.0179849" m22="0.498116" m32="0.892997"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip L Hand"
			m00="0.586701" m10="0.0490764" m20="-0.808315" m30="0.23965"
			m01="0.240177" m11="-0.963796" m21="0.115812" m31="0.209092"
			m02="-0.773367" m12="-0.262086" m22="-0.577247" m32="0.70342"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip L Finger1"
			m00="0.555662" m10="-0.194758" m20="-0.808275" m30="0.347944"
			m01="-0.175356" m11="-0.97776" m21="0.115045" m31="0.253425"
			m02="-0.812705" m12="0.0778099" m22="-0.577456" m32="0.560671"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip L Finger11"
			m00="0.329193" m10="-0.488183" m20="-0.808275" m30="0.389894"
			m01="-0.724834" m11="-0.67925" m21="0.115045" m31="0.240186"
			m02="-0.605184" m12="0.547994" m22="-0.577456" m32="0.499317"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip L Finger01"
			m00="0.485446" m10="-0.828795" m20="0.278282" m30="0.482779"
			m01="-0.714325" m11="-0.192487" m21="0.672821" m31="0.169185"
			m02="-0.504066" m12="-0.525402" m22="-0.685471" m32="0.738411"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip Prop1"
			m00="0.868353" m10="-0.15567" m20="0.470882" m30="0.0686252"
			m01="0.445879" m11="0.660771" m21="-0.603799" m31="-0.33415"
			m02="-0.217152" m12="0.734267" m22="0.643193" m32="0.504053"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip Ponytail2"
			m00="-0.408388" m10="-0.912564" m20="-0.0211323" m30="0.22056"
			m01="-0.872942" m11="0.383681" m21="0.301265" m31="-0.096241"
			m02="-0.266816" m12="0.141481" m22="-0.953306" m32="1.38451"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip Ponytail1"
			m00="0.14189" m10="-0.953788" m20="0.264869" m30="0.24743"
			m01="0.8151" m11="0.264404" m21="0.515463" m31="-0.00686588"
			m02="-0.561675" m12="0.142755" m22="0.814949" m32="1.3734"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip L Calf"
			m00="-0.817871" m10="0.54913" m20="-0.17188" m30="0.0772887"
			m01="0.0676356" m11="-0.204896" m21="-0.976444" m31="0.105758"
			m02="-0.571412" m12="-0.810231" m22="0.130438" m32="0.194729"
			m03="0" m13="0" m23="0" m33="1"/>
	</frame>
	<frame index="1">
		<transform name="peon bip Pelvis"
			m00="0.0121485" m10="0.840247" m20="0.542067" m30="-0.0614396"
			m01="0.0865535" m11="-0.540956" m21="0.836585" m31="0.0447856"
			m02="0.996173" m12="0.0367546" m22="-0.0792982" m32="0.382253"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip Spine"
			m00="0.130877" m10="0.829547" m20="0.542884" m30="-0.0852367"
			m01="0.0469425" m11="-0.552165" m21="0.832412" m31="0.0662898"
			m02="0.990287" m12="-0.0834596" m22="-0.111207" m32="0.557727"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip L Thigh"
			m00="0.322898" m10="0.934201" m20="-0.151676" m30="0.0186332"
			m01="-0.274678" m11="-0.0608619" m21="-0.959608" m31="0.168364"
			m02="-0.905698" m12="0.351517" m22="0.236952" m32="0.370539"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip R Thigh"
			m00="0.741531" m10="0.503034" m20="-0.443947" m30="-0.141512"
			m01="-0.278995" m11="-0.370577" m21="-0.885909" m31="-0.0787923"
			m02="-0.610159" m12="0.780788" m22="-0.13445" m32="0.393967"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip L Toe0"
			m00="0.981547" m10="-4.67907e-006" m20="0.191219" m30="0.0921542"
			m01="0.191219" m11="-0.000549165" m21="-0.981547" m31="0.137063"
			m02="0.000109624" m12="1.0" m22="-0.000538174" m32="0.00526455"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip L Foot"
			m00="4.73757e-006" m10="0.981547" m20="0.191219" m30="-0.0248488"
			m01="0.000549176" m11="0.191219" m21="-0.981547" m31="0.114204"
			m02="-1.0" m12="0.000109683" m22="-0.000538174" m32="0.12337"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip Spine2"
			m00="0.286074" m10="0.720563" m20="0.631625" m30="-0.0286663"
			m01="-0.409812" m11="-0.503839" m21="0.760395" m31="0.0661857"
			m02="0.86615" m12="-0.476377" m22="0.15116" m32="0.884658"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip Spine1"
			m00="0.210753" m10="0.806795" m20="0.551964" m30="-0.0635926"
			m01="-0.04843" m11="-0.555336" m21="0.830215" m31="0.0741648"
			m02="0.976339" m12="-0.201702" m22="-0.0779658" m32="0.722332"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip R Clavicle"
			m00="-0.631623" m10="-0.720792" m20="-0.2855" m30="0.016133"
			m01="-0.760396" m11="0.504163" m21="0.409411" m31="-0.0106197"
			m02="-0.151161" m12="0.475687" m22="-0.866529" m32="1.03365"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip R UpperArm"
			m00="-0.5612" m10="-0.827416" m20="0.0208848" m30="-0.0194859"
			m01="-0.591274" m11="0.418437" m21="0.689423" m31="-0.0535004"
			m02="-0.579179" m12="0.374556" m22="-0.724057" m32="1.02513"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip Neck"
			m00="0.424403" m10="0.648793" m20="0.631625" m30="0.0208722"
			m01="-0.502297" m11="-0.4117" m21="0.760395" m31="-0.00482069"
			m02="0.753379" m12="-0.639977" m22="0.151159" m32="1.03485"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip Head"
			m00="0.164314" m10="0.927022" m20="0.337093" m30="0.0626811"
			m01="0.0602729" m11="-0.350535" m21="0.934608" m31="-0.0543031"
			m02="0.984565" m12="-0.133252" m22="-0.113472" m32="1.10907"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip R Forearm"
			m00="-0.0391413" m10="-0.999015" m20="0.0208848" m30="-0.135254"
			m01="-0.723096" m11="0.0427435" m21="0.689423" m31="-0.175472"
			m02="-0.689637" m12="0.0118832" m22="-0.724057" m32="0.905653"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip R Hand"
			m00="-0.0878173" m10="0.99295" m20="-0.079609" m30="-0.143813"
			m01="-0.726046" m11="-0.118519" m21="-0.677356" m31="-0.333598"
			m02="-0.682016" m12="-0.00168382" m22="0.731335" m32="0.754844"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip R Calf"
			m00="-0.30389" m10="0.842949" m20="-0.443947" m30="0.0155037"
			m01="0.290011" m11="-0.362021" m21="-0.885909" m31="-0.137868"
			m02="-0.907494" m12="-0.397968" m22="-0.13445" m32="0.264768"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip R Foot"
			m00="0.291323" m10="0.707957" m20="-0.643373" m30="-0.0224467"
			m01="-0.240761" m11="-0.596635" m21="-0.765546" m31="-0.101651"
			m02="-0.925832" m12="0.37792" m22="-0.00336453" m32="0.151438"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip R Toe0"
			m00="0.707957" m10="-0.291323" m20="-0.643373" m30="0.0963539"
			m01="-0.596635" m11="0.240761" m21="-0.765546" m31="-0.20121"
			m02="0.37792" m12="0.925832" m22="-0.00336453" m32="0.0871291"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip L UpperArm"
			m00="0.404627" m10="-0.559148" m20="0.723623" m30="0.0613321"
			m01="0.634163" m11="0.741684" m21="0.218499" m31="0.0437944"
			m02="-0.658873" m12="0.370485" m22="0.654696" m32="1.04447"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip L Clavicle"
			m00="0.631623" m10="-0.720792" m20="0.2855" m30="0.0257132"
			m01="0.760396" m11="0.504163" m21="-0.40941" m31="0.000913692"
			m02="0.151161" m12="0.475687" m22="0.866529" m32="1.03595"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip L Forearm"
			m00="0.673213" m10="-0.152164" m20="0.723623" m30="0.144801"
			m01="-0.0143196" m11="0.975732" m21="0.218499" m31="0.174614"
			m02="-0.73931" m12="-0.157458" m22="0.654696" m32="0.908555"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip L Hand"
			m00="0.806591" m10="-0.142954" m20="-0.573564" m30="0.292018"
			m01="0.0516052" m11="-0.949582" m21="0.309244" m31="0.171482"
			m02="-0.588853" m12="-0.279032" m22="-0.758547" m32="0.746884"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip L Finger1"
			m00="0.719962" m10="-0.390574" m20="-0.573678" m30="0.440899"
			m01="-0.251816" m11="-0.917292" m21="0.308487" m31="0.181008"
			m02="-0.646717" m12="-0.0776382" m22="-0.758769" m32="0.638193"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip L Finger11"
			m00="0.416052" m10="-0.705545" m20="-0.573678" m30="0.495252"
			m01="-0.68821" m11="-0.65666" m21="0.308487" m31="0.161997"
			m02="-0.594363" m12="0.266464" m22="-0.758769" m32="0.589369"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip L Finger01"
			m00="0.518856" m10="-0.596799" m20="0.612062" m30="0.499997"
			m01="-0.820191" m11="-0.145698" m21="0.553225" m31="0.0751601"
			m02="-0.240988" m12="-0.789052" m22="-0.565085" m32="0.848083"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip Prop1"
			m00="0.992151" m10="0.0829951" m20="-0.0935262" m30="-0.0853121"
			m01="-0.123889" m11="0.753786" m21="-0.645335" m31="-0.319641"
			m02="0.0169391" m12="0.651857" m22="0.758153" m32="0.536222"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip Ponytail2"
			m00="-0.510366" m10="-0.855627" m20="-0.086194" m30="0.135535"
			m01="-0.84698" m11="0.482785" m21="0.222585" m31="-0.0990821"
			m02="-0.148837" m12="0.186604" m22="-0.971096" m32="1.3709"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip Ponytail1"
			m00="0.176474" m10="-0.935684" m20="0.305535" m30="0.167222"
			m01="0.86757" m11="0.294487" m21="0.400748" m31="-0.0112325"
			m02="-0.46495" m12="0.194351" m22="0.863741" m32="1.36024"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip L Calf"
			m00="-0.895679" m10="0.418035" m20="-0.151676" m30="0.0870055"
			m01="0.0320491" m11="-0.279508" m21="-0.959608" m31="0.110202"
			m02="-0.443545" m12="-0.864362" m22="0.236952" m32="0.178761"
			m03="0" m13="0" m23="0" m33="1"/>
	</frame>
	<frame index="2">
		<transform name="peon bip Pelvis"
			m00="0.0366946" m10="0.726919" m20="0.685742" m30="-0.108536"
			m01="0.154762" m11="-0.682059" m21="0.714734" m31="0.0958725"
			m02="0.98727" m12="0.0799001" m22="-0.137528" m32="0.37545"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip Spine"
			m00="0.117848" m10="0.687784" m20="0.716285" m30="-0.126415"
			m01="0.0701954" m11="-0.725277" m21="0.684869" m31="0.134038"
			m02="0.990548" m12="-0.0304304" m22="-0.133752" m32="0.548779"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip L Thigh"
			m00="0.440143" m10="0.897555" m20="0.0258845" m30="-0.00723984"
			m01="-0.304103" m11="0.176125" m21="-0.936216" m31="0.201451"
			m02="-0.844864" m12="0.404197" m22="0.350469" m32="0.355134"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip R Thigh"
			m00="0.72604" m10="0.392672" m20="-0.564512" m30="-0.209832"
			m01="-0.426016" m11="-0.387561" m21="-0.8175" m31="-0.00970581"
			m02="-0.539793" m12="0.834029" m22="-0.114101" m32="0.395765"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip L Toe0"
			m00="0.981547" m10="-4.69114e-006" m20="0.191219" m30="0.0921542"
			m01="0.191219" m11="-0.000549697" m21="-0.981547" m31="0.137063"
			m02="0.000109708" m12="1.0" m22="-0.000538607" m32="0.00526453"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip L Foot"
			m00="4.74964e-006" m10="0.981547" m20="0.191219" m30="-0.0248488"
			m01="0.000549708" m11="0.191219" m21="-0.981547" m31="0.114204"
			m02="-1.0" m12="0.000109767" m22="-0.000538607" m32="0.12337"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip Spine2"
			m00="0.0958296" m10="0.553869" m20="0.827071" m30="-0.0828364"
			m01="-0.454133" m11="-0.715053" m21="0.531472" m31="0.135368"
			m02="0.885765" m12="-0.426531" m22="0.183007" m32="0.877569"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip Spine1"
			m00="0.145336" m10="0.640499" m20="0.754081" m30="-0.106914"
			m01="-0.0633921" m11="-0.754579" m21="0.65314" m31="0.145804"
			m02="0.987349" m12="-0.142728" m22="-0.0690653" m32="0.71342"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip R Clavicle"
			m00="-0.827069" m10="-0.553947" m20="-0.0953884" m30="-0.0724972"
			m01="-0.531474" m11="0.715413" m21="0.453563" m31="0.0526155"
			m02="-0.183008" m12="0.425825" m22="-0.886104" m32="1.02972"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip R UpperArm"
			m00="-0.776659" m10="-0.501551" m20="0.381113" m30="-0.119138"
			m01="-0.290551" m11="0.822044" m21="0.489717" m31="0.0226443"
			m02="-0.55891" m12="0.26961" m22="-0.784175" m32="1.0194"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip Neck"
			m00="0.295128" m10="0.478387" m20="0.82707" m30="-0.0662624"
			m01="-0.687681" m11="-0.494603" m21="0.531473" m31="0.056685"
			m02="0.663321" m12="-0.725613" m22="0.183006" m32="1.03117"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip Head"
			m00="0.195468" m10="0.944096" m20="0.265471" m30="-0.0371887"
			m01="-0.0150204" m11="-0.267778" m21="0.963363" m31="-0.01106"
			m02="0.980595" m12="-0.192294" m22="-0.0381613" m32="1.09651"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip R Forearm"
			m00="-0.218904" m10="-0.898239" m20="0.381113" m30="-0.279352"
			m01="-0.776272" m11="0.396962" m21="0.489717" m31="-0.0372925"
			m02="-0.591171" m12="-0.188646" m22="-0.784175" m32="0.904108"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip R Hand"
			m00="-0.265551" m10="0.753429" m20="-0.60152" m30="-0.327222"
			m01="-0.760233" m11="-0.54734" m21="-0.349949" m31="-0.207046"
			m02="-0.592899" m12="0.364366" m22="0.718129" m32="0.774832"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip R Calf"
			m00="0.0557825" m10="0.823538" m20="-0.564512" m30="-0.0560958"
			m01="0.100133" m11="-0.567157" m21="-0.8175" m31="-0.0999129"
			m02="-0.993409" m12="-0.0109241" m22="-0.114101" m32="0.281466"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip R Foot"
			m00="0.405003" m10="0.572047" m20="-0.713256" m30="-0.0491295"
			m01="-0.371987" m11="-0.609525" m21="-0.700075" m31="-0.0874081"
			m02="-0.835224" m12="0.548855" m22="-0.034065" m32="0.157407"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip R Toe0"
			m00="0.572047" m10="-0.405003" m20="-0.713256" m30="0.0668981"
			m01="-0.609525" m11="0.371987" m21="-0.700075" m31="-0.204003"
			m02="0.548855" m12="0.835224" m22="-0.034065" m32="0.124176"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip L UpperArm"
			m00="0.623839" m10="-0.556568" m20="0.548686" m30="-0.013312"
			m01="0.62359" m11="0.777665" m21="0.0798336" m31="0.090648"
			m02="-0.471126" m12="0.292352" m22="0.832208" m32="1.04282"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip L Clavicle"
			m00="0.827069" m10="-0.553947" m20="0.0953885" m30="-0.0599526"
			m01="0.531474" m11="0.715413" m21="-0.453563" m31="0.0606767"
			m02="0.183008" m12="0.425825" m22="0.886104" m32="1.0325"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip L Forearm"
			m00="0.817634" m10="0.174411" m20="0.548686" m30="0.115378"
			m01="-0.258907" m11="0.962597" m21="0.0798336" m31="0.219286"
			m02="-0.51424" m12="-0.207333" m22="0.832208" m32="0.945633"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip L Hand"
			m00="0.949468" m10="-0.207648" m20="-0.235355" m30="0.294176"
			m01="-0.107411" m11="-0.919559" m21="0.377988" m31="0.162669"
			m02="-0.294911" m12="-0.333608" m22="-0.895395" m32="0.83318"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip L Finger1"
			m00="0.888487" m10="-0.393854" m20="-0.23552" m30="0.46943"
			m01="-0.289896" m11="-0.879567" m21="0.377256" m31="0.142843"
			m02="-0.355739" m12="-0.26691" m22="-0.895661" m32="0.778745"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip L Finger11"
			m00="0.650042" m10="-0.722478" m20="-0.23552" m30="0.536506"
			m01="-0.623949" m11="-0.684373" m21="0.377256" m31="0.120957"
			m02="-0.433743" m12="-0.0982795" m22="-0.895661" m32="0.751889"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip L Finger01"
			m00="0.483865" m10="-0.217173" m20="0.847768" m30="0.437692"
			m01="-0.86285" m11="-0.280183" m21="0.420698" m31="0.043098"
			m02="0.146166" m12="-0.935058" m22="-0.322958" m32="1.00207"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip Prop1"
			m00="0.745188" m10="0.283618" m20="-0.603536" m30="-0.215302"
			m01="-0.54666" m11="0.778138" m21="-0.309295" m31="-0.278991"
			m02="0.381913" m12="0.560412" m22="0.734902" m32="0.591227"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip Ponytail2"
			m00="-0.474824" m10="-0.864307" m20="-0.165881" m30="0.0481751"
			m01="-0.870426" m11="0.433354" m21="0.233587" m31="-0.0733029"
			m02="-0.130006" m12="0.255299" m22="-0.958082" m32="1.3509"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip Ponytail1"
			m00="0.104989" m10="-0.951123" m20="0.290416" m30="0.0731326"
			m01="0.956323" m11="0.176671" m21="0.23288" m31="0.017258"
			m02="-0.272806" m12="0.253282" m22="0.92813" m32="1.34731"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip L Calf"
			m00="-0.887296" m10="0.460474" m20="0.0258845" m30="0.0859586"
			m01="-0.183007" m11="-0.300012" m21="-0.936216" m31="0.137058"
			m02="-0.423338" m12="-0.835438" m22="0.350469" m32="0.176238"
			m03="0" m13="0" m23="0" m33="1"/>
	</frame>
	<frame index="3">
		<transform name="peon bip Pelvis"
			m00="0.0527695" m10="0.664045" m20="0.745828" m30="-0.138052"
			m01="0.185253" m11="-0.740414" m21="0.646118" m31="0.127558"
			m02="0.981273" m12="0.104071" m22="-0.162087" m32="0.372195"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip Spine"
			m00="0.111374" m10="0.607347" m20="0.786591" m30="-0.152041"
			m01="0.0844696" m11="-0.794436" m21="0.601445" m31="0.173177"
			m02="0.990182" m12="-0.000542259" m22="-0.139782" m32="0.544074"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip L Thigh"
			m00="0.496273" m10="0.836412" m20="0.232654" m30="-0.0278801"
			m01="-0.270067" m11="0.40342" m21="-0.874252" m31="0.223"
			m02="-0.825092" m12="0.371036" m22="0.426094" m32="0.348252"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip R Thigh"
			m00="0.68239" m10="0.398288" m20="-0.612952" m30="-0.248224"
			m01="-0.450962" m11="-0.430564" m21="-0.781823" m31="0.0321151"
			m02="-0.575306" m12="0.809927" m22="-0.1142" m32="0.396138"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip L Toe0"
			m00="0.981547" m10="-4.87482e-006" m20="0.191219" m30="0.0921542"
			m01="0.191219" m11="-0.00055003" m21="-0.981547" m31="0.137063"
			m02="0.000109943" m12="1.0" m22="-0.000538938" m32="0.0052646"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip L Foot"
			m00="4.93332e-006" m10="0.981547" m20="0.191219" m30="-0.0248488"
			m01="0.000550042" m11="0.191219" m21="-0.981547" m31="0.114204"
			m02="-1.0" m12="0.000110002" m22="-0.000538938" m32="0.12337"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip Spine2"
			m00="-0.00271484" m10="0.455471" m20="0.890246" m30="-0.115534"
			m01="-0.449669" m11="-0.795722" m21="0.405739" m31="0.177472"
			m02="0.893191" m12="-0.399215" m22="0.206972" m32="0.873605"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip Spine1"
			m00="0.109098" m10="0.544301" m20="0.831766" m30="-0.133603"
			m01="-0.05995" m11="-0.831634" m21="0.552078" m31="0.187325"
			m02="0.992222" m12="-0.110095" m22="-0.0580992" m32="0.70865"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip R Clavicle"
			m00="-0.890245" m10="-0.455471" m20="0.00307758" m30="-0.122757"
			m01="-0.405741" m11="0.796079" m21="0.449035" m31="0.0964471"
			m02="-0.206973" m12="0.398503" m22="-0.893509" m32="1.02687"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip R UpperArm"
			m00="-0.813186" m10="-0.236468" m20="0.5318" m30="-0.17296"
			m01="-0.0832702" m11="0.951611" m21="0.295809" m31="0.0735663"
			m02="-0.576015" m12="0.196265" m22="-0.793528" m32="1.01519"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip Neck"
			m00="0.213594" m10="0.402292" m20="0.890246" m30="-0.116037"
			m01="-0.773226" m11="-0.487336" m21="0.40574" m31="0.0995624"
			m02="0.597075" m12="-0.775025" m22="0.206971" m32="1.0285"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip Head"
			m00="0.213256" m10="0.957166" m20="0.195846" m30="-0.094995"
			m01="-0.0684345" m11="-0.18533" m21="0.98029" m31="0.0233902"
			m02="0.974597" m12="-0.222455" m22="0.0259804" m32="1.08732"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip R Forearm"
			m00="-0.332479" m10="-0.778875" m20="0.5318" m30="-0.340709"
			m01="-0.788853" m11="0.53871" m21="0.295809" m31="0.0563888"
			m02="-0.516884" m12="-0.321161" m22="-0.793528" m32="0.89637"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip R Hand"
			m00="-0.374478" m10="0.494813" m20="-0.784172" m30="-0.413415"
			m01="-0.764249" m11="-0.643607" m21="-0.0411521" m31="-0.116116"
			m02="-0.525061" m12="0.583893" m22="0.619177" m32="0.783338"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip R Calf"
			m00="0.342111" m10="0.712214" m20="-0.612952" m30="-0.10373"
			m01="-0.13233" m11="-0.609296" m21="-0.781823" m31="-0.0633744"
			m02="-0.930295" m12="0.348582" m22="-0.1142" m32="0.274319"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip R Foot"
			m00="0.447032" m10="0.501168" m20="-0.740941" m30="-0.0610067"
			m01="-0.431567" m11="-0.6047" m21="-0.669393" m31="-0.0799"
			m02="-0.783526" m12="0.619006" m22="-0.0540325" m32="0.158142"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip R Toe0"
			m00="0.501168" m10="-0.447032" m20="-0.740941" m30="0.0515364"
			m01="-0.6047" m11="0.431567" m21="-0.669393" m31="-0.202958"
			m02="0.619006" m12="0.783526" m22="-0.0540325" m32="0.13938"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip L UpperArm"
			m00="0.715121" m10="-0.572312" m20="0.401324" m30="-0.0590504"
			m01="0.615793" m11="0.787488" m21="0.0257205" m31="0.125482"
			m02="-0.330758" m12="0.228739" m22="0.915575" m32="1.04168"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip L Clavicle"
			m00="0.890245" m10="-0.455471" m20="-0.00307751" m30="-0.109254"
			m01="0.405741" m11="0.796079" m21="-0.449035" m31="0.102601"
			m02="0.206973" m12="0.398503" m22="0.893509" m32="1.03"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip L Forearm"
			m00="0.843952" m10="0.355928" m20="0.401324" m30="0.0884694"
			m01="-0.398826" m11="0.916666" m21="0.0257205" m31="0.252512"
			m02="-0.358725" m12="-0.181765" m22="0.915575" m32="0.973446"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip L Hand"
			m00="0.976538" m10="-0.214872" m20="-0.0142522" m30="0.273023"
			m01="-0.193835" m11="-0.905904" m21="0.376518" m31="0.165297"
			m02="-0.0938143" m12="-0.364922" m22="-0.9263" m32="0.895001"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip L Finger1"
			m00="0.941438" m10="-0.336878" m20="-0.0144233" m30="0.453273"
			m01="-0.307109" m11="-0.874334" m21="0.375797" m31="0.129519"
			m02="-0.139209" m12="-0.34936" m22="-0.92659" m32="0.877684"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip L Finger11"
			m00="0.771525" m10="-0.636035" m20="-0.0144233" m30="0.524347"
			m01="-0.585284" m11="-0.718484" m21="0.375797" m31="0.106334"
			m02="-0.249383" m12="-0.281495" m22="-0.92659" m32="0.867175"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="peon bip L Finger01"
			m00="0.369503" m10="0.00946294" m20="0.929181" m30="0.366894"