<?xml version="1.0" encoding="UTF-8" standalone="yes"?>

<!DOCTYPE mesh [
        <!ELEMENT mesh       (polygons, skeleton?)>
        <!ELEMENT polygons   (polygon+)>
        <!ELEMENT polygon    (vertex, vertex, vertex)>
        <!ELEMENT vertex     (skin+)>
        <!ELEMENT skin        EMPTY>
        <!ELEMENT skeleton   (bones, init_pose)>
        <!ELEMENT bones      (bone+)>
        <!ELEMENT init_pose  (transform+)>
        <!ELEMENT bone        EMPTY>
        <!ELEMENT transform   EMPTY>
        <!ATTLIST mesh texture CDATA #IMPLIED>
        <!ATTLIST vertex x CDATA #REQUIRED>
        <!ATTLIST vertex y CDATA #REQUIRED>
        <!ATTLIST vertex z CDATA #REQUIRED>
        <!ATTLIST vertex r CDATA #REQUIRED>
        <!ATTLIST vertex g CDATA #REQUIRED>
        <!ATTLIST vertex b CDATA #REQUIRED>
        <!ATTLIST vertex a CDATA #REQUIRED>
        <!ATTLIST vertex nx CDATA #REQUIRED>
        <!ATTLIST vertex ny CDATA #REQUIRED>
        <!ATTLIST vertex nz CDATA #REQUIRED>
        <!ATTLIST vertex u CDATA #REQUIRED>
        <!ATTLIST vertex v CDATA #REQUIRED>
        <!ATTLIST vertex u2 CDATA #IMPLIED>
        <!ATTLIST vertex v2 CDATA #IMPLIED>
        <!ATTLIST skin bone CDATA #REQUIRED>
        <!ATTLIST skin weight CDATA #REQUIRED>
        <!ATTLIST transform name CDATA #REQUIRED>
        <!ATTLIST transform m00 CDATA #REQUIRED>
        <!ATTLIST transform m01 CDATA #REQUIRED>
        <!ATTLIST transform m02 CDATA #REQUIRED>
        <!ATTLIST transform m03 CDATA #REQUIRED>
        <!ATTLIST transform m10 CDATA #REQUIRED>
        <!ATTLIST transform m11 CDATA #REQUIRED>
        <!ATTLIST transform m12 CDATA #REQUIRED>
        <!ATTLIST transform m13 CDATA #REQUIRED>
        <!ATTLIST transform m20 CDATA #REQUIRED>
        <!ATTLIST transform m21 CDATA #REQUIRED>
        <!ATTLIST transform m22 CDATA #REQUIRED>
        <!ATTLIST transform m23 CDATA #REQUIRED>
        <!ATTLIST transform m30 CDATA #REQUIRED>
        <!ATTLIST transform m31 CDATA #REQUIRED>
        <!ATTLIST transform m32 CDATA #REQUIRED>
        <!ATTLIST transform m33 CDATA #REQUIRED>
        <!ATTLIST bone name CDATA #REQUIRED>
        <!ATTLIST bone parent CDATA #REQUIRED>
        ]>

<mesh>
    <polygons>
        <polygon>
            <vertex x="-1.05392" y="-1.3562" z="0.00911107" r="1" g="1" b="1" a="1" nx="0.739305" ny="0.559483"
                    nz="0.374709" u="0.268706" v="0.854051">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="-1.25777" y="-1.82481" z="0.679687" r="1" g="1" b="1" a="1" nx="0.14159" ny="-0.950401"
                    nz="-0.276929" u="0.253303" v="0.936052">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="-1.03812" y="-1.59159" z="0.00917986" r="1" g="1" b="1" a="1" nx="0.752545" ny="-0.657803"
                    nz="0.0311798" u="0.2508" v="0.858234">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
        </polygon>
        <polygon>
            <vertex x="-1.25777" y="-1.82481" z="0.679687" r="1" g="1" b="1" a="1" nx="0.14159" ny="-0.950401"
                    nz="-0.276929" u="0.253303" v="0.936052">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="-1.54676" y="-1.71409" z="0.743452" r="1" g="1" b="1" a="1" nx="-0.71729" ny="-0.521101"
                    nz="-0.462547" u="0.231307" v="0.945987">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="-1.03812" y="-1.59159" z="0.00917986" r="1" g="1" b="1" a="1" nx="0.752545" ny="-0.657803"
                    nz="0.0311798" u="0.2508" v="0.858234">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
        </polygon>
        <polygon>
            <vertex x="-1.54676" y="-1.71409" z="0.743452" r="1" g="1" b="1" a="1" nx="-0.71729" ny="-0.521101"
                    nz="-0.462547" u="0.231307" v="0.945987">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="-1.56713" y="-1.39868" z="0.679686" r="1" g="1" b="1" a="1" nx="-0.855423" ny="0.416371"
                    nz="-0.308035" u="0.211301" v="0.936421">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="-1.2574" y="-1.28907" z="0.00917961" r="1" g="1" b="1" a="1" nx="-0.403999" ny="0.91474"
                    nz="-0.00599384" u="0.212318" v="0.858317">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
        </polygon>
        <polygon>
            <vertex x="-1.56713" y="-1.39868" z="0.679686" r="1" g="1" b="1" a="1" nx="-0.855423" ny="0.416371"
                    nz="-0.308035" u="0.253303" v="0.936052">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="-1.05392" y="-1.3562" z="0.00911107" r="1" g="1" b="1" a="1" nx="0.739305" ny="0.559483"
                    nz="0.374709" u="0.268706" v="0.854051">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="-1.2574" y="-1.28907" z="0.00917961" r="1" g="1" b="1" a="1" nx="-0.403999" ny="0.91474"
                    nz="-0.00599384" u="0.2508" v="0.858234">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
        </polygon>
        <polygon>
            <vertex x="-1.56713" y="-1.39868" z="0.679686" r="1" g="1" b="1" a="1" nx="-0.855423" ny="0.416371"
                    nz="-0.308035" u="0.253303" v="0.936052">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="-1.26725" y="-1.51144" z="0.61376" r="1" g="1" b="1" a="1" nx="0.746236" ny="0.532164"
                    nz="0.399917" u="0.274303" v="0.925527">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="-1.05392" y="-1.3562" z="0.00911107" r="1" g="1" b="1" a="1" nx="0.739305" ny="0.559483"
                    nz="0.374709" u="0.268706" v="0.854051">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
        </polygon>
        <polygon>
            <vertex x="-1.26725" y="-1.51144" z="0.61376" r="1" g="1" b="1" a="1" nx="0.746236" ny="0.532164"
                    nz="0.399917" u="0.274303" v="0.925527">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="-1.25777" y="-1.82481" z="0.679687" r="1" g="1" b="1" a="1" nx="0.14159" ny="-0.950401"
                    nz="-0.276929" u="0.253303" v="0.936052">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="-1.05392" y="-1.3562" z="0.00911107" r="1" g="1" b="1" a="1" nx="0.739305" ny="0.559483"
                    nz="0.374709" u="0.268706" v="0.854051">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
        </polygon>
        <polygon>
            <vertex x="-1.03812" y="-1.59159" z="0.00917986" r="1" g="1" b="1" a="1" nx="0.752545" ny="-0.657803"
                    nz="0.0311798" u="0.2508" v="0.858234">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="-1.54676" y="-1.71409" z="0.743452" r="1" g="1" b="1" a="1" nx="-0.71729" ny="-0.521101"
                    nz="-0.462547" u="0.231307" v="0.945987">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="-1.25166" y="-1.49971" z="0.00912726" r="1" g="1" b="1" a="1" nx="-0.744556" ny="-0.497968"
                    nz="-0.444595" u="0.23164" v="0.862323">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
        </polygon>
        <polygon>
            <vertex x="-1.54676" y="-1.71409" z="0.743452" r="1" g="1" b="1" a="1" nx="-0.71729" ny="-0.521101"
                    nz="-0.462547" u="0.231307" v="0.945987">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="-1.2574" y="-1.28907" z="0.00917961" r="1" g="1" b="1" a="1" nx="-0.403999" ny="0.91474"
                    nz="-0.00599384" u="0.212318" v="0.858317">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="-1.25166" y="-1.49971" z="0.00912726" r="1" g="1" b="1" a="1" nx="-0.744556" ny="-0.497968"
                    nz="-0.444595" u="0.23164" v="0.862323">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
        </polygon>
        <polygon>
            <vertex x="-0.681526" y="-3.2282" z="-0.0286333" r="1" g="1" b="1" a="1" nx="0.950776" ny="-0.309874"
                    nz="0.00152292" u="0.0126347" v="1.16871">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="-0.705097" y="-3.02947" z="-0.0329164" r="1" g="1" b="1" a="1" nx="0.775224" ny="0.59549"
                    nz="0.21076" u="0.0125555" v="1.15647">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="-0.867068" y="-3.78589" z="2.33233" r="1" g="1" b="1" a="1" nx="0.905343" ny="-0.424239"
                    nz="0.0193852" u="0.130242" v="1.17191">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
        </polygon>
        <polygon>
            <vertex x="-0.705097" y="-3.02947" z="-0.0329164" r="1" g="1" b="1" a="1" nx="0.775224" ny="0.59549"
                    nz="0.21076" u="0.0125555" v="1.15647">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="-0.886705" y="-2.94606" z="-0.0180716" r="1" g="1" b="1" a="1" nx="-0.0236042" ny="0.968413"
                    nz="0.248233" u="0.012675" v="1.14349">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="-1.0366" y="-3.554" z="2.33937" r="1" g="1" b="1" a="1" nx="-0.116303" ny="0.956656"
                    nz="0.266988" u="0.130152" v="1.15406">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
        </polygon>
        <polygon>
            <vertex x="-0.886705" y="-2.94606" z="-0.0180716" r="1" g="1" b="1" a="1" nx="-0.0236042" ny="0.968413"
                    nz="0.248233" u="0.012674" v="1.21881">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="-1.04565" y="-3.06345" z="0.00121356" r="1" g="1" b="1" a="1" nx="-0.866095" ny="0.493542"
                    nz="0.0793424" u="0.0125548" v="1.2065">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="-1.0366" y="-3.554" z="2.33937" r="1" g="1" b="1" a="1" nx="-0.116303" ny="0.956656"
                    nz="0.266988" u="0.130088" v="1.20755">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
        </polygon>
        <polygon>
            <vertex x="-1.04565" y="-3.06345" z="0.00121356" r="1" g="1" b="1" a="1" nx="-0.866095" ny="0.493542"
                    nz="0.0793424" u="0.0125548" v="1.2065">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="-1.02433" y="-3.2624" z="0.00572264" r="1" g="1" b="1" a="1" nx="-0.824912" ny="-0.538611"
                    nz="-0.171516" u="0.0126345" v="1.19377">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="-1.1514" y="-3.81574" z="2.35451" r="1" g="1" b="1" a="1" nx="-0.807556" ny="-0.573319"
                    nz="-0.138413" u="0.130193" v="1.18971">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
        </polygon>
        <polygon>
            <vertex x="-1.02433" y="-3.2624" z="0.00572264" r="1" g="1" b="1" a="1" nx="-0.824912" ny="-0.538611"
                    nz="-0.171516" u="0.0126345" v="1.19377">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="-0.841819" y="-3.34373" z="-0.00927853" r="1" g="1" b="1" a="1" nx="0.142588" ny="-0.967168"
                    nz="-0.210367" u="0.0125551" v="1.18143">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="-1.1514" y="-3.81574" z="2.35451" r="1" g="1" b="1" a="1" nx="-0.807556" ny="-0.573319"
                    nz="-0.138413" u="0.130193" v="1.18971">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
        </polygon>
        <polygon>
            <vertex x="-0.841819" y="-3.34373" z="-0.00927853" r="1" g="1" b="1" a="1" nx="0.142588" ny="-0.967168"
                    nz="-0.210367" u="0.0125551" v="1.18143">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="-0.681526" y="-3.2282" z="-0.0286333" r="1" g="1" b="1" a="1" nx="0.950776" ny="-0.309874"
                    nz="0.00152292" u="0.0126347" v="1.16871">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="-0.867068" y="-3.78589" z="2.33233" r="1" g="1" b="1" a="1" nx="0.905343" ny="-0.424239"
                    nz="0.0193852" u="0.130242" v="1.17191">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
        </polygon>
        <polygon>
            <vertex x="-0.867068" y="-3.78589" z="2.33233" r="1" g="1" b="1" a="1" nx="0.905343" ny="-0.424239"
                    nz="0.0193852" u="0.247926" v="1.17185">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="-1.12081" y="-3.8129" z="3.50355" r="1" g="1" b="1" a="1" nx="-0.127063" ny="0.97111"
                    nz="0.20199" u="0.318211" v="1.15404">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="-0.969146" y="-4.0197" z="3.49468" r="1" g="1" b="1" a="1" nx="0.90783" ny="-0.418552"
                    nz="-0.0256641" u="0.318535" v="1.17185">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
        </polygon>
        <polygon>
            <vertex x="-0.867068" y="-3.78589" z="2.33233" r="1" g="1" b="1" a="1" nx="0.905343" ny="-0.424239"
                    nz="0.0193852" u="0.247926" v="1.17185">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="-1.0366" y="-3.554" z="2.33937" r="1" g="1" b="1" a="1" nx="-0.116303" ny="0.956656"
                    nz="0.266988" u="0.247919" v="1.15404">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="-1.12081" y="-3.8129" z="3.50355" r="1" g="1" b="1" a="1" nx="-0.127063" ny="0.97111"
                    nz="0.20199" u="0.318211" v="1.15404">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
        </polygon>
        <polygon>
            <vertex x="-1.0366" y="-3.554" z="2.33937" r="1" g="1" b="1" a="1" nx="-0.116303" ny="0.956656"
                    nz="0.266988" u="0.247914" v="1.20752">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="-1.22387" y="-4.04785" z="3.52369" r="1" g="1" b="1" a="1" nx="-0.816415" ny="-0.561397"
                    nz="-0.135276" u="0.31855" v="1.18965">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="-1.12081" y="-3.8129" z="3.50355" r="1" g="1" b="1" a="1" nx="-0.127063" ny="0.97111"
                    nz="0.20199" u="0.318208" v="1.20751">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
        </polygon>
        <polygon>
            <vertex x="-1.0366" y="-3.554" z="2.33937" r="1" g="1" b="1" a="1" nx="-0.116303" ny="0.956656"
                    nz="0.266988" u="0.247914" v="1.20752">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="-1.1514" y="-3.81574" z="2.35451" r="1" g="1" b="1" a="1" nx="-0.807556" ny="-0.573319"
                    nz="-0.138413" u="0.247924" v="1.18966">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="-1.22387" y="-4.04785" z="3.52369" r="1" g="1" b="1" a="1" nx="-0.816415" ny="-0.561397"
                    nz="-0.135276" u="0.31855" v="1.18965">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
        </polygon>
        <polygon>
            <vertex x="-1.1514" y="-3.81574" z="2.35451" r="1" g="1" b="1" a="1" nx="-0.807556" ny="-0.573319"
                    nz="-0.138413" u="0.247924" v="1.18966">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="-0.969146" y="-4.0197" z="3.49468" r="1" g="1" b="1" a="1" nx="0.90783" ny="-0.418552"
                    nz="-0.0256641" u="0.318535" v="1.17185">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="-1.22387" y="-4.04785" z="3.52369" r="1" g="1" b="1" a="1" nx="-0.816415" ny="-0.561397"
                    nz="-0.135276" u="0.31855" v="1.18965">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
        </polygon>
        <polygon>
            <vertex x="-1.1514" y="-3.81574" z="2.35451" r="1" g="1" b="1" a="1" nx="-0.807556" ny="-0.573319"
                    nz="-0.138413" u="0.247924" v="1.18966">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="-0.867068" y="-3.78589" z="2.33233" r="1" g="1" b="1" a="1" nx="0.905343" ny="-0.424239"
                    nz="0.0193852" u="0.247926" v="1.17185">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="-0.969146" y="-4.0197" z="3.49468" r="1" g="1" b="1" a="1" nx="0.90783" ny="-0.418552"
                    nz="-0.0256641" u="0.318535" v="1.17185">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
        </polygon>
        <polygon>
            <vertex x="-0.969146" y="-4.0197" z="3.49468" r="1" g="1" b="1" a="1" nx="0.90783" ny="-0.418552"
                    nz="-0.0256641" u="0.130242" v="1.17191">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="-1.14848" y="-4.05761" z="4.6651" r="1" g="1" b="1" a="1" nx="-0.351675" ny="1.73497"
                    nz="0.357239" u="0.247919" v="1.15404">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="-1.01479" y="-4.23965" z="4.65578" r="1" g="1" b="1" a="1" nx="1.34213" ny="-0.864792"
                    nz="-0.110721" u="0.247926" v="1.17185">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
        </polygon>
        <polygon>
            <vertex x="-0.969146" y="-4.0197" z="3.49468" r="1" g="1" b="1" a="1" nx="0.90783" ny="-0.418552"
                    nz="-0.0256641" u="0.130242" v="1.17191">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="-1.12081" y="-3.8129" z="3.50355" r="1" g="1" b="1" a="1" nx="-0.127063" ny="0.97111"
                    nz="0.20199" u="0.130152" v="1.15406">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="-1.14848" y="-4.05761" z="4.6651" r="1" g="1" b="1" a="1" nx="-0.351675" ny="1.73497"
                    nz="0.357239" u="0.247919" v="1.15404">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
        </polygon>
        <polygon>
            <vertex x="-1.12081" y="-3.8129" z="3.50355" r="1" g="1" b="1" a="1" nx="-0.127063" ny="0.97111"
                    nz="0.20199" u="0.130088" v="1.20755">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="-1.23938" y="-4.26522" z="4.68664" r="1" g="1" b="1" a="1" nx="-1.0655" ny="-0.84657"
                    nz="-0.172349" u="0.247924" v="1.18966">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="-1.14848" y="-4.05761" z="4.6651" r="1" g="1" b="1" a="1" nx="-0.351675" ny="1.73497"
                    nz="0.357239" u="0.247914" v="1.20752">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
        </polygon>
        <polygon>
            <vertex x="-1.12081" y="-3.8129" z="3.50355" r="1" g="1" b="1" a="1" nx="-0.127063" ny="0.97111"
                    nz="0.20199" u="0.130088" v="1.20755">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="-1.22387" y="-4.04785" z="3.52369" r="1" g="1" b="1" a="1" nx="-0.816415" ny="-0.561397"
                    nz="-0.135276" u="0.130193" v="1.18971">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="-1.23938" y="-4.26522" z="4.68664" r="1" g="1" b="1" a="1" nx="-1.0655" ny="-0.84657"
                    nz="-0.172349" u="0.247924" v="1.18966">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
        </polygon>
        <polygon>
            <vertex x="-1.22387" y="-4.04785" z="3.52369" r="1" g="1" b="1" a="1" nx="-0.816415" ny="-0.561397"
                    nz="-0.135276" u="0.130193" v="1.18971">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="-1.01479" y="-4.23965" z="4.65578" r="1" g="1" b="1" a="1" nx="1.34213" ny="-0.864792"
                    nz="-0.110721" u="0.247926" v="1.17185">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="-1.23938" y="-4.26522" z="4.68664" r="1" g="1" b="1" a="1" nx="-1.0655" ny="-0.84657"
                    nz="-0.172349" u="0.247924" v="1.18966">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
        </polygon>
        <polygon>
            <vertex x="-1.22387" y="-4.04785" z="3.52369" r="1" g="1" b="1" a="1" nx="-0.816415" ny="-0.561397"
                    nz="-0.135276" u="0.130193" v="1.18971">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="-0.969146" y="-4.0197" z="3.49468" r="1" g="1" b="1" a="1" nx="0.90783" ny="-0.418552"
                    nz="-0.0256641" u="0.130242" v="1.17191">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="-1.01479" y="-4.23965" z="4.65578" r="1" g="1" b="1" a="1" nx="1.34213" ny="-0.864792"
                    nz="-0.110721" u="0.247926" v="1.17185">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
        </polygon>
        <polygon>
            <vertex x="-1.01479" y="-4.23965" z="4.65578" r="1" g="1" b="1" a="1" nx="1.34213" ny="-0.864792"
                    nz="-0.110721" u="0.247926" v="1.17185">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="-1.13168" y="-4.22769" z="5.82996" r="1" g="1" b="1" a="1" nx="-0.11279" ny="0.983335"
                    nz="0.142586" u="0.318211" v="1.15404">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="-1.0147" y="-4.38687" z="5.8205" r="1" g="1" b="1" a="1" nx="0.909664" ny="-0.409943"
                    nz="-0.0667678" u="0.318535" v="1.17185">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
        </polygon>
        <polygon>
            <vertex x="-1.01479" y="-4.23965" z="4.65578" r="1" g="1" b="1" a="1" nx="1.34213" ny="-0.864792"
                    nz="-0.110721" u="0.247926" v="1.17185">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="-1.14848" y="-4.05761" z="4.6651" r="1" g="1" b="1" a="1" nx="-0.351675" ny="1.73497"
                    nz="0.357239" u="0.247919" v="1.15404">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="-1.13168" y="-4.22769" z="5.82996" r="1" g="1" b="1" a="1" nx="-0.11279" ny="0.983335"
                    nz="0.142586" u="0.318211" v="1.15404">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
        </polygon>
        <polygon>
            <vertex x="-1.14848" y="-4.05761" z="4.6651" r="1" g="1" b="1" a="1" nx="-0.351675" ny="1.73497"
                    nz="0.357239" u="0.247914" v="1.20752">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="-1.21117" y="-4.40987" z="5.85212" r="1" g="1" b="1" a="1" nx="-0.815435" ny="-0.578157"
                    nz="-0.0282836" u="0.31855" v="1.18965">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="-1.13168" y="-4.22769" z="5.82996" r="1" g="1" b="1" a="1" nx="-0.11279" ny="0.983335"
                    nz="0.142586" u="0.318208" v="1.20751">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
        </polygon>
        <polygon>
            <vertex x="-1.14848" y="-4.05761" z="4.6651" r="1" g="1" b="1" a="1" nx="-0.351675" ny="1.73497"
                    nz="0.357239" u="0.247914" v="1.20752">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="-1.23938" y="-4.26522" z="4.68664" r="1" g="1" b="1" a="1" nx="-1.0655" ny="-0.84657"
                    nz="-0.172349" u="0.247924" v="1.18966">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="-1.21117" y="-4.40987" z="5.85212" r="1" g="1" b="1" a="1" nx="-0.815435" ny="-0.578157"
                    nz="-0.0282836" u="0.31855" v="1.18965">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
        </polygon>
        <polygon>
            <vertex x="-1.23938" y="-4.26522" z="4.68664" r="1" g="1" b="1" a="1" nx="-1.0655" ny="-0.84657"
                    nz="-0.172349" u="0.247924" v="1.18966">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="-1.0147" y="-4.38687" z="5.8205" r="1" g="1" b="1" a="1" nx="0.909664" ny="-0.409943"
                    nz="-0.0667678" u="0.318535" v="1.17185">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="-1.21117" y="-4.40987" z="5.85212" r="1" g="1" b="1" a="1" nx="-0.815435" ny="-0.578157"
                    nz="-0.0282836" u="0.31855" v="1.18965">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
        </polygon>
        <polygon>
            <vertex x="-1.23938" y="-4.26522" z="4.68664" r="1" g="1" b="1" a="1" nx="-1.0655" ny="-0.84657"
                    nz="-0.172349" u="0.247924" v="1.18966">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="-1.01479" y="-4.23965" z="4.65578" r="1" g="1" b="1" a="1" nx="1.34213" ny="-0.864792"
                    nz="-0.110721" u="0.247926" v="1.17185">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="-1.0147" y="-4.38687" z="5.8205" r="1" g="1" b="1" a="1" nx="0.909664" ny="-0.409943"
                    nz="-0.0667678" u="0.318535" v="1.17185">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
        </polygon>
        <polygon>
            <vertex x="-1.0147" y="-4.38687" z="5.8205" r="1" g="1" b="1" a="1" nx="0.909664" ny="-0.409943"
                    nz="-0.0667678" u="0.247926" v="1.17185">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="-1.06886" y="-4.38863" z="6.98776" r="1" g="1" b="1" a="1" nx="-0.111887" ny="0.982867"
                    nz="0.146472" u="0.318211" v="1.15404">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="-0.973177" y="-4.51879" z="6.97898" r="1" g="1" b="1" a="1" nx="0.906485" ny="-0.412805"
                    nz="-0.0887592" u="0.318535" v="1.17185">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
        </polygon>
        <polygon>
            <vertex x="-1.0147" y="-4.38687" z="5.8205" r="1" g="1" b="1" a="1" nx="0.909664" ny="-0.409943"
                    nz="-0.0667678" u="0.247926" v="1.17185">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="-1.13168" y="-4.22769" z="5.82996" r="1" g="1" b="1" a="1" nx="-0.11279" ny="0.983335"
                    nz="0.142586" u="0.247919" v="1.15404">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="-1.06886" y="-4.38863" z="6.98776" r="1" g="1" b="1" a="1" nx="-0.111887" ny="0.982867"
                    nz="0.146472" u="0.318211" v="1.15404">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
        </polygon>
        <polygon>
            <vertex x="-1.13168" y="-4.22769" z="5.82996" r="1" g="1" b="1" a="1" nx="-0.11279" ny="0.983335"
                    nz="0.142586" u="0.247914" v="1.20752">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="-1.13372" y="-4.53811" z="7.00862" r="1" g="1" b="1" a="1" nx="-0.811386" ny="-0.582934"
                    nz="0.0429128" u="0.31855" v="1.18965">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="-1.06886" y="-4.38863" z="6.98776" r="1" g="1" b="1" a="1" nx="-0.111887" ny="0.982867"
                    nz="0.146472" u="0.318208" v="1.20751">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
        </polygon>
        <polygon>
            <vertex x="-1.13168" y="-4.22769" z="5.82996" r="1" g="1" b="1" a="1" nx="-0.11279" ny="0.983335"
                    nz="0.142586" u="0.247914" v="1.20752">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="-1.21117" y="-4.40987" z="5.85212" r="1" g="1" b="1" a="1" nx="-0.815435" ny="-0.578157"
                    nz="-0.0282836" u="0.247924" v="1.18966">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>