<?xml version="1.0" encoding="UTF-8" standalone="yes"?>

<!DOCTYPE mesh [
        <!ELEMENT mesh       (polygons, skeleton?)>
        <!ELEMENT polygons   (polygon+)>
        <!ELEMENT polygon    (vertex, vertex, vertex)>
        <!ELEMENT vertex     (skin+)>
        <!ELEMENT skin        EMPTY>
        <!ELEMENT skeleton   (bones, init_pose)>
        <!ELEMENT bones      (bone+)>
        <!ELEMENT init_pose  (transform+)>
        <!ELEMENT bone        EMPTY>
        <!ELEMENT transform   EMPTY>
        <!ATTLIST mesh texture CDATA #IMPLIED>
        <!ATTLIST vertex x CDATA #REQUIRED>
        <!ATTLIST vertex y CDATA #REQUIRED>
        <!ATTLIST vertex z CDATA #REQUIRED>
        <!ATTLIST vertex r CDATA #REQUIRED>
        <!ATTLIST vertex g CDATA #REQUIRED>
        <!ATTLIST vertex b CDATA #REQUIRED>
        <!ATTLIST vertex a CDATA #REQUIRED>
        <!ATTLIST vertex nx CDATA #REQUIRED>
        <!ATTLIST vertex ny CDATA #REQUIRED>
        <!ATTLIST vertex nz CDATA #REQUIRED>
        <!ATTLIST vertex u CDATA #REQUIRED>
        <!ATTLIST vertex v CDATA #REQUIRED>
        <!ATTLIST vertex u2 CDATA #IMPLIED>
        <!ATTLIST vertex v2 CDATA #IMPLIED>
        <!ATTLIST skin bone CDATA #REQUIRED>
        <!ATTLIST skin weight CDATA #REQUIRED>
        <!ATTLIST transform name CDATA #REQUIRED>
        <!ATTLIST transform m00 CDATA #REQUIRED>
        <!ATTLIST transform m01 CDATA #REQUIRED>
        <!ATTLIST transform m02 CDATA #REQUIRED>
        <!ATTLIST transform m03 CDATA #REQUIRED>
        <!ATTLIST transform m10 CDATA #REQUIRED>
        <!ATTLIST transform m11 CDATA #REQUIRED>
        <!ATTLIST transform m12 CDATA #REQUIRED>
        <!ATTLIST transform m13 CDATA #REQUIRED>
        <!ATTLIST transform m20 CDATA #REQUIRED>
        <!ATTLIST transform m21 CDATA #REQUIRED>
        <!ATTLIST transform m22 CDATA #REQUIRED>
        <!ATTLIST transform m23 CDATA #REQUIRED>
        <!ATTLIST transform m30 CDATA #REQUIRED>
        <!ATTLIST transform m31 CDATA #REQUIRED>
        <!ATTLIST transform m32 CDATA #REQUIRED>
        <!ATTLIST transform m33 CDATA #REQUIRED>
        <!ATTLIST bone name CDATA #REQUIRED>
        <!ATTLIST bone parent CDATA #REQUIRED>
        ]>

<mesh>
    <polygons>
        <polygon>
            <vertex x="5.142" y="-1.59252" z="4.00796" r="1" g="1" b="1" a="1" nx="0.958679" ny="-0.0476429"
                    nz="0.280471" u="0.166437" v="0.587341">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="5.0209" y="-0.621321" z="4.00796" r="1" g="1" b="1" a="1" nx="0.921613" ny="0.271663"
                    nz="0.27718" u="0.24083" v="0.59351">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="4.44615" y="-0.742634" z="5.50827" r="1" g="1" b="1" a="1" nx="0.888936" ny="0.281329"
                    nz="0.361452" u="0.224039" v="0.718004">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
        </polygon>
        <polygon>
            <vertex x="4.44615" y="-0.742634" z="5.50827" r="1" g="1" b="1" a="1" nx="0.888936" ny="0.281329"
                    nz="0.361452" u="0.224039" v="0.718004">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="4.54465" y="-1.47692" z="5.50827" r="1" g="1" b="1" a="1" nx="0.923808" ny="-0.0467434"
                    nz="0.379993" u="0.160854" v="0.711374">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="5.142" y="-1.59252" z="4.00796" r="1" g="1" b="1" a="1" nx="0.958679" ny="-0.0476429"
                    nz="0.280471" u="0.166437" v="0.587341">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
        </polygon>
        <polygon>
            <vertex x="5.0209" y="-0.621321" z="4.00796" r="1" g="1" b="1" a="1" nx="0.921613" ny="0.271663"
                    nz="0.27718" u="0.0172827" v="0.5952">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="4.59592" y="0.24933" z="4.00796" r="1" g="1" b="1" a="1" nx="0.773422" ny="0.56881" nz="0.279774"
                    u="0.0914942" v="0.587151">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="4.09797" y="-0.0655893" z="5.50827" r="1" g="1" b="1" a="1" nx="0.746015" ny="0.561061"
                    nz="0.358708" u="0.0981704" v="0.711789">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
        </polygon>
        <polygon>
            <vertex x="4.09797" y="-0.0655893" z="5.50827" r="1" g="1" b="1" a="1" nx="0.746015" ny="0.561061"
                    nz="0.358708" u="0.0981704" v="0.711789">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="4.44615" y="-0.742634" z="5.50827" r="1" g="1" b="1" a="1" nx="0.888936" ny="0.281329"
                    nz="0.361452" u="0.0357292" v="0.718044">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="5.0209" y="-0.621321" z="4.00796" r="1" g="1" b="1" a="1" nx="0.921613" ny="0.271663"
                    nz="0.27718" u="0.0172827" v="0.5952">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
        </polygon>
        <polygon>
            <vertex x="4.09797" y="-0.0655893" z="5.50827" r="1" g="1" b="1" a="1" nx="0.746015" ny="0.561061"
                    nz="0.358708" u="0.0981704" v="0.711789">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="3.90354" y="0.890656" z="4.00796" r="1" g="1" b="1" a="1" nx="1.09597" ny="1.46302" nz="0.691685"
                    u="0.166437" v="0.587341">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="3.56044" y="0.444969" z="5.50827" r="1" g="1" b="1" a="1" nx="0.450857" ny="0.822233"
                    nz="0.347362" u="0.160854" v="0.711374">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
        </polygon>
        <polygon>
            <vertex x="3.90354" y="0.890656" z="4.00796" r="1" g="1" b="1" a="1" nx="1.09597" ny="1.46302" nz="0.691685"
                    u="0.166437" v="0.587341">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="4.09797" y="-0.0655893" z="5.50827" r="1" g="1" b="1" a="1" nx="0.746015" ny="0.561061"
                    nz="0.358708" u="0.0981704" v="0.711789">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="4.59592" y="0.24933" z="4.00796" r="1" g="1" b="1" a="1" nx="0.773422" ny="0.56881" nz="0.279774"
                    u="0.0914942" v="0.587151">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
        </polygon>
        <polygon>
            <vertex x="3.90354" y="0.890656" z="4.00796" r="1" g="1" b="1" a="1" nx="1.09597" ny="1.46302" nz="0.691685"
                    u="0.166437" v="0.587341">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="2.70482" y="0.659244" z="5.57347" r="1" g="1" b="1" a="1" nx="0.230083" ny="0.827891"
                    nz="0.298554" u="0.224039" v="0.718004">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="3.56044" y="0.444969" z="5.50827" r="1" g="1" b="1" a="1" nx="0.450857" ny="0.822233"
                    nz="0.347362" u="0.160854" v="0.711374">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
        </polygon>
        <polygon>
            <vertex x="1.14038" y="-3.34816" z="5.50827" r="1" g="1" b="1" a="1" nx="-0.448701" ny="-0.635899"
                    nz="0.627932" u="0.161811" v="0.710742">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="0.911576" y="-4.42071" z="4.39306" r="1" g="1" b="1" a="1" nx="0.123881" ny="-0.870676"
                    nz="0.476" u="0.140549" v="0.587581">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="1.34975" y="-4.34944" z="4.27943" r="1" g="1" b="1" a="1" nx="0.277369" ny="-0.888965"
                    nz="0.364427" u="0.20457" v="0.590416">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
        </polygon>
        <polygon>
            <vertex x="0.911576" y="-4.42071" z="4.39306" r="1" g="1" b="1" a="1" nx="0.123881" ny="-0.870676"
                    nz="0.476" u="0.140549" v="0.587581">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="0.854317" y="-2.9742" z="5.50827" r="1" g="1" b="1" a="1" nx="-0.00306853" ny="-0.677546"
                    nz="0.735474" u="0.136255" v="0.712249">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="0.489899" y="-4.45164" z="4.39306" r="1" g="1" b="1" a="1" nx="0.085361" ny="-0.892235"
                    nz="0.44343" u="0.0905767" v="0.587625">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
        </polygon>
        <polygon>
            <vertex x="0.911576" y="-4.42071" z="4.39306" r="1" g="1" b="1" a="1" nx="0.123881" ny="-0.870676"
                    nz="0.476" u="0.140549" v="0.587581">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="1.14038" y="-3.34816" z="5.50827" r="1" g="1" b="1" a="1" nx="-0.448701" ny="-0.635899"
                    nz="0.627932" u="0.161811" v="0.710742">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="0.854317" y="-2.9742" z="5.50827" r="1" g="1" b="1" a="1" nx="-0.00306853" ny="-0.677546"
                    nz="0.735474" u="0.136255" v="0.712249">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
        </polygon>
        <polygon>
            <vertex x="1.75956" y="-3.54745" z="5.50827" r="1" g="1" b="1" a="1" nx="0.0144238" ny="-0.859021"
                    nz="0.511736" u="0.224336" v="0.718144">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="1.14038" y="-3.34816" z="5.50827" r="1" g="1" b="1" a="1" nx="-0.448701" ny="-0.635899"
                    nz="0.627932" u="0.161811" v="0.710742">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="1.34975" y="-4.34944" z="4.27943" r="1" g="1" b="1" a="1" nx="0.277369" ny="-0.888965"
                    nz="0.364427" u="0.20457" v="0.590416">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
        </polygon>
        <polygon>
            <vertex x="1.75956" y="-3.54745" z="5.50827" r="1" g="1" b="1" a="1" nx="0.0144238" ny="-0.859021"
                    nz="0.511736" u="0.224336" v="0.718144">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="1.34975" y="-4.34944" z="4.27943" r="1" g="1" b="1" a="1" nx="0.277369" ny="-0.888965"
                    nz="0.364427" u="0.20457" v="0.590416">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="1.67092" y="-4.29884" z="4.00796" r="1" g="1" b="1" a="1" nx="0.282381" ny="-0.924955"
                    nz="0.254399" u="0.240664" v="0.593282">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
        </polygon>
        <polygon>
            <vertex x="1.67092" y="-4.29884" z="4.00796" r="1" g="1" b="1" a="1" nx="0.282381" ny="-0.924955"
                    nz="0.254399" u="0.0172827" v="0.5952">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="2.62412" y="-4.07003" z="4.00796" r="1" g="1" b="1" a="1" nx="0.279965" ny="-0.914011"
                    nz="0.293604" u="0.0914942" v="0.587151">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="2.48193" y="-3.40239" z="5.50827" r="1" g="1" b="1" a="1" nx="0.254923" ny="-0.871411"
                    nz="0.419115" u="0.0981704" v="0.711789">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
        </polygon>
        <polygon>
            <vertex x="2.48193" y="-3.40239" z="5.50827" r="1" g="1" b="1" a="1" nx="0.254923" ny="-0.871411"
                    nz="0.419115" u="0.0981704" v="0.711789">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="1.75956" y="-3.54745" z="5.50827" r="1" g="1" b="1" a="1" nx="0.0144238" ny="-0.859021"
                    nz="0.511736" u="0.0357292" v="0.718044">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="1.67092" y="-4.29884" z="4.00796" r="1" g="1" b="1" a="1" nx="0.282381" ny="-0.924955"
                    nz="0.254399" u="0.0172827" v="0.5952">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
        </polygon>
        <polygon>
            <vertex x="2.62412" y="-4.07003" z="4.00796" r="1" g="1" b="1" a="1" nx="0.279965" ny="-0.914011"
                    nz="0.293604" u="0.0914942" v="0.587151">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="3.58213" y="-3.70582" z="4.00796" r="1" g="1" b="1" a="1" nx="0.416382" ny="-0.86" nz="0.295001"
                    u="0.166437" v="0.587341">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="3.23514" y="-3.12299" z="5.50827" r="1" g="1" b="1" a="1" nx="0.395411" ny="-0.820903"
                    nz="0.412028" u="0.160854" v="0.711374">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
        </polygon>
        <polygon>
            <vertex x="3.23514" y="-3.12299" z="5.50827" r="1" g="1" b="1" a="1" nx="0.395411" ny="-0.820903"
                    nz="0.412028" u="0.160854" v="0.711374">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="2.48193" y="-3.40239" z="5.50827" r="1" g="1" b="1" a="1" nx="0.254923" ny="-0.871411"
                    nz="0.419115" u="0.0981704" v="0.711789">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="2.62412" y="-4.07003" z="4.00796" r="1" g="1" b="1" a="1" nx="0.279965" ny="-0.914011"
                    nz="0.293604" u="0.0914942" v="0.587151">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
        </polygon>
        <polygon>
            <vertex x="3.58213" y="-3.70582" z="4.00796" r="1" g="1" b="1" a="1" nx="0.416382" ny="-0.86" nz="0.295001"
                    u="0.166437" v="0.587341">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="4.40872" y="-3.2157" z="4.00796" r="1" g="1" b="1" a="1" nx="0.640964" ny="-0.709393"
                    nz="0.293134" u="0.24083" v="0.59351">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="3.90023" y="-2.72069" z="5.50827" r="1" g="1" b="1" a="1" nx="0.588332" ny="-0.688135"
                    nz="0.424661" u="0.224039" v="0.718004">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
        </polygon>
        <polygon>
            <vertex x="3.90023" y="-2.72069" z="5.50827" r="1" g="1" b="1" a="1" nx="0.588332" ny="-0.688135"
                    nz="0.424661" u="0.224039" v="0.718004">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="3.23514" y="-3.12299" z="5.50827" r="1" g="1" b="1" a="1" nx="0.395411" ny="-0.820903"
                    nz="0.412028" u="0.160854" v="0.711374">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="3.58213" y="-3.70582" z="4.00796" r="1" g="1" b="1" a="1" nx="0.416382" ny="-0.86" nz="0.295001"
                    u="0.166437" v="0.587341">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
        </polygon>
        <polygon>
            <vertex x="4.40872" y="-3.2157" z="4.00796" r="1" g="1" b="1" a="1" nx="0.640964" ny="-0.709393"
                    nz="0.293134" u="0.0172827" v="0.5952">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="4.94208" y="-2.49734" z="4.00796" r="1" g="1" b="1" a="1" nx="0.867639" ny="-0.402601"
                    nz="0.291743" u="0.0914942" v="0.587151">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="4.36037" y="-2.16138" z="5.50827" r="1" g="1" b="1" a="1" nx="0.813162" ny="-0.407285"
                    nz="0.415795" u="0.0981704" v="0.711789">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
        </polygon>
        <polygon>
            <vertex x="4.36037" y="-2.16138" z="5.50827" r="1" g="1" b="1" a="1" nx="0.813162" ny="-0.407285"
                    nz="0.415795" u="0.0981704" v="0.711789">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="3.90023" y="-2.72069" z="5.50827" r="1" g="1" b="1" a="1" nx="0.588332" ny="-0.688135"
                    nz="0.424661" u="0.0357292" v="0.718044">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="4.40872" y="-3.2157" z="4.00796" r="1" g="1" b="1" a="1" nx="0.640964" ny="-0.709393"
                    nz="0.293134" u="0.0172827" v="0.5952">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
        </polygon>
        <polygon>
            <vertex x="4.94208" y="-2.49734" z="4.00796" r="1" g="1" b="1" a="1" nx="0.867639" ny="-0.402601"
                    nz="0.291743" u="0.0914942" v="0.587151">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="5.142" y="-1.59252" z="4.00796" r="1" g="1" b="1" a="1" nx="0.958679" ny="-0.0476429"
                    nz="0.280471" u="0.166437" v="0.587341">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="4.54465" y="-1.47692" z="5.50827" r="1" g="1" b="1" a="1" nx="0.923808" ny="-0.0467434"
                    nz="0.379993" u="0.160854" v="0.711374">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
        </polygon>
        <polygon>
            <vertex x="4.54465" y="-1.47692" z="5.50827" r="1" g="1" b="1" a="1" nx="0.923808" ny="-0.0467434"
                    nz="0.379993" u="0.160854" v="0.711374">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="4.36037" y="-2.16138" z="5.50827" r="1" g="1" b="1" a="1" nx="0.813162" ny="-0.407285"
                    nz="0.415795" u="0.0981704" v="0.711789">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="4.94208" y="-2.49734" z="4.00796" r="1" g="1" b="1" a="1" nx="0.867639" ny="-0.402601"
                    nz="0.291743" u="0.0914942" v="0.587151">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
        </polygon>
        <polygon>
            <vertex x="4.37945" y="2.87643" z="4.00796" r="1" g="1" b="1" a="1" nx="0.961249" ny="0.112387"
                    nz="0.251734" u="0.0914942" v="0.587151">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="4.0854" y="3.78536" z="4.00796" r="1" g="1" b="1" a="1" nx="0.832265" ny="0.485064" nz="0.268416"
                    u="0.166437" v="0.587341">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="3.73742" y="3.57546" z="5.50827" r="1" g="1" b="1" a="1" nx="0.834244" ny="0.488027"
                    nz="0.256644" u="0.160854" v="0.711374">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
        </polygon>
        <polygon>
            <vertex x="3.73742" y="3.57546" z="5.50827" r="1" g="1" b="1" a="1" nx="0.834244" ny="0.488027"
                    nz="0.256644" u="0.160854" v="0.711374">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="4.01034" y="2.79869" z="5.50827" r="1" g="1" b="1" a="1" nx="0.962241" ny="0.131016"
                    nz="0.238592" u="0.0981704" v="0.711789">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="4.37945" y="2.87643" z="4.00796" r="1" g="1" b="1" a="1" nx="0.961249" ny="0.112387"
                    nz="0.251734" u="0.0914942" v="0.587151">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
        </polygon>
        <polygon>
            <vertex x="4.0854" y="3.78536" z="4.00796" r="1" g="1" b="1" a="1" nx="0.832265" ny="0.485064" nz="0.268416"
                    u="0.166437" v="0.587341">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="3.43325" y="4.49576" z="4.00796" r="1" g="1" b="1" a="1" nx="0.566274" ny="0.787372"
                    nz="0.243677" u="0.24083" v="0.59351">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="3.18801" y="4.18866" z="5.50827" r="1" g="1" b="1" a="1" nx="0.577851" ny="0.775092"
                    nz="0.255577" u="0.224039" v="0.718004">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
        </polygon>
        <polygon>
            <vertex x="3.18801" y="4.18866" z="5.50827" r="1" g="1" b="1" a="1" nx="0.577851" ny="0.775092"
                    nz="0.255577" u="0.224039" v="0.718004">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="3.73742" y="3.57546" z="5.50827" r="1" g="1" b="1" a="1" nx="0.834244" ny="0.488027"
                    nz="0.256644" u="0.160854" v="0.711374">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="4.0854" y="3.78536" z="4.00796" r="1" g="1" b="1" a="1" nx="0.832265" ny="0.485064" nz="0.268416"
                    u="0.166437" v="0.587341">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
        </polygon>
        <polygon>
            <vertex x="3.43325" y="4.49576" z="4.00796" r="1" g="1" b="1" a="1" nx="0.566274" ny="0.787372"
                    nz="0.243677" u="0.0172827" v="0.5952">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="2.55208" y="4.89399" z="4.00796" r="1" g="1" b="1" a="1" nx="0.22824" ny="0.944923" nz="0.234577"
                    u="0.0914942" v="0.587151">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="2.44576" y="4.54494" z="5.50827" r="1" g="1" b="1" a="1" nx="0.235932" ny="0.941545"
                    nz="0.240479" u="0.0981704" v="0.711789">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
        </polygon>
        <polygon>
            <vertex x="2.44576" y="4.54494" z="5.50827" r="1" g="1" b="1" a="1" nx="0.235932" ny="0.941545"
                    nz="0.240479" u="0.0981704" v="0.711789">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="3.18801" y="4.18866" z="5.50827" r="1" g="1" b="1" a="1" nx="0.577851" ny="0.775092"
                    nz="0.255577" u="0.0357292" v="0.718044">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="3.43325" y="4.49576" z="4.00796" r="1" g="1" b="1" a="1" nx="0.566274" ny="0.787372"
                    nz="0.243677" u="0.0172827" v="0.5952">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
        </polygon>
        <polygon>
            <vertex x="2.55208" y="4.89399" z="4.00796" r="1" g="1" b="1" a="1" nx="0.22824" ny="0.944923" nz="0.234577"
                    u="0.0914942" v="0.587151">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="1.5947" y="4.93796" z="4.00796" r="1" g="1" b="1" a="1" nx="-0.13728" ny="0.965085" nz="0.223079"
                    u="0.166437" v="0.587341">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="1.62367" y="4.59005" z="5.50827" r="1" g="1" b="1" a="1" nx="-0.140669" ny="0.963458"
                    nz="0.227951" u="0.160854" v="0.711374">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
        </polygon>
        <polygon>
            <vertex x="1.62367" y="4.59005" z="5.50827" r="1" g="1" b="1" a="1" nx="-0.140669" ny="0.963458"
                    nz="0.227951" u="0.160854" v="0.711374">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="2.44576" y="4.54494" z="5.50827" r="1" g="1" b="1" a="1" nx="0.235932" ny="0.941545"
                    nz="0.240479" u="0.0981704" v="0.711789">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="2.55208" y="4.89399" z="4.00796" r="1" g="1" b="1" a="1" nx="0.22824" ny="0.944923" nz="0.234577"
                    u="0.0914942" v="0.587151">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
        </polygon>
        <polygon>
            <vertex x="1.5947" y="4.93796" z="4.00796" r="1" g="1" b="1" a="1" nx="-0.13728" ny="0.965085" nz="0.223079"
                    u="0.166437" v="0.587341">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="0.688509" y="4.62813" z="4.00796" r="1" g="1" b="1" a="1" nx="-0.489017" ny="0.843818"
                    nz="0.220985" u="0.24083" v="0.59351">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="0.844962" y="4.31629" z="5.50827" r="1" g="1" b="1" a="1" nx="-0.504661" ny="0.833708"
                    nz="0.224162" u="0.224039" v="0.718004">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
        </polygon>
        <polygon>
            <vertex x="0.844962" y="4.31629" z="5.50827" r="1" g="1" b="1" a="1" nx="-0.504661" ny="0.833708"
                    nz="0.224162" u="0.224039" v="0.718004">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="1.62367" y="4.59005" z="5.50827" r="1" g="1" b="1" a="1" nx="-0.140669" ny="0.963458"
                    nz="0.227951" u="0.160854" v="0.711374">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="1.5947" y="4.93796" z="4.00796" r="1" g="1" b="1" a="1" nx="-0.13728" ny="0.965085" nz="0.223079"
                    u="0.166437" v="0.587341">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
        </polygon>
        <polygon>
            <vertex x="0.688509" y="4.62813" z="4.00796" r="1" g="1" b="1" a="1" nx="-0.489017" ny="0.843818"
                    nz="0.220985" u="0.0172827" v="0.5952">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="-0.0276868" y="3.99986" z="4.00796" r="1" g="1" b="1" a="1" nx="-0.771617" ny="0.595807"
                    nz="0.222758" u="0.0914942" v="0.587151">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="0.231726" y="3.74622" z="5.50827" r="1" g="1" b="1" a="1" nx="-0.790854" ny="0.564649"
                    nz="0.236055" u="0.0981704" v="0.711789">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
        </polygon>
        <polygon>
            <vertex x="0.231726" y="3.74622" z="5.50827" r="1" g="1" b="1" a="1" nx="-0.790854" ny="0.564649"
                    nz="0.236055" u="0.0981704" v="0.711789">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="0.844962" y="4.31629" z="5.50827" r="1" g="1" b="1" a="1" nx="-0.504661" ny="0.833708"
                    nz="0.224162" u="0.0357292" v="0.718044">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="0.688509" y="4.62813" z="4.00796" r="1" g="1" b="1" a="1" nx="-0.489017" ny="0.843818"
                    nz="0.220985" u="0.0172827" v="0.5952">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
        </polygon>
        <polygon>
            <vertex x="-0.220024" y="2.99038" z="5.05132" r="1" g="1" b="1" a="1" nx="-3.64866" ny="1.05236"
                    nz="0.986957" u="0.163062" v="0.678483">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="-0.101013" y="2.95842" z="5.50827" r="1" g="1" b="1" a="1" nx="-0.94167" ny="0.213453"
                    nz="0.260185" u="0.160854" v="0.711374">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="0.231726" y="3.74622" z="5.50827" r="1" g="1" b="1" a="1" nx="-0.790854" ny="0.564649"
                    nz="0.236055" u="0.0981704" v="0.711789">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
        </polygon>
        <polygon>
            <vertex x="-0.179087" y="3.69819" z="4.00796" r="1" g="1" b="1" a="1" nx="-1.85445" ny="0.893117"
                    nz="0.479193" u="0.118231" v="0.586717">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="-0.220024" y="2.99038" z="5.05132" r="1" g="1" b="1" a="1" nx="-3.64866" ny="1.05236"
                    nz="0.986957" u="0.163062" v="0.678483">
                <skin bone="dummy_bone" weight="1"/>
            </vertex>
            <vertex x="0.231726" y="3.74622" z="5.50827" r="1" g="1" b="1" a="1" nx="-0.790854" ny="0.564649"
                    nz="0.236055" u="0.0981704" v="0.711789">