<?xml version="1.0" encoding="UTF-8" standalone="yes"?>

<!DOCTYPE mesh [
	<!ELEMENT mesh       (polygons)>
	<!ELEMENT polygons   (polygon+)>
	<!ELEMENT polygon    (vertex+)>
	<!ELEMENT vertex     (skin+)>

	<!ELEMENT skin        EMPTY>

	<!ATTLIST vertex x CDATA #REQUIRED>
	<!ATTLIST vertex y CDATA #REQUIRED>
	<!ATTLIST vertex z CDATA #REQUIRED>
	<!ATTLIST vertex r CDATA #REQUIRED>
	<!ATTLIST vertex g CDATA #REQUIRED>
	<!ATTLIST vertex b CDATA #REQUIRED>
	<!ATTLIST vertex a CDATA #REQUIRED>
	<!ATTLIST vertex nx CDATA #REQUIRED>
	<!ATTLIST vertex ny CDATA #REQUIRED>
	<!ATTLIST vertex nz CDATA #REQUIRED>
	<!ATTLIST vertex u CDATA #REQUIRED>
	<!ATTLIST vertex v CDATA #REQUIRED>
	<!ATTLIST skin bone CDATA #REQUIRED>
	<!ATTLIST skin weight CDATA #REQUIRED>
]>

<mesh>
	<polygons>
		<polygon>
			<vertex x="1.7271" y="-3.31796" z="0.314029"
				r="1" g="1" b="1" a="1"
				nx="-0.760194" ny="1.15064" nz="0.454535"
				u="0.417747" v="0.125898">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="1.52804" y="-3.33737" z="0.0302405"
				r="1" g="1" b="1" a="1"
				nx="-0.385334" ny="0.732827" nz="-0.560787"
				u="0.375504" v="0.118775">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="1.54347" y="-3.47936" z="0.415507"
				r="1" g="1" b="1" a="1"
				nx="-0.396582" ny="0.338608" nz="0.853269"
				u="0.419236" v="0.0934196">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="1.96727" y="-3.55357" z="0.205041"
				r="1" g="1" b="1" a="1"
				nx="2.03801" ny="-1.69319" nz="-0.019731"
				u="0.472284" v="0.125721">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="1.88653" y="-3.45654" z="0.387327"
				r="1" g="1" b="1" a="1"
				nx="0.913012" ny="-0.81884" nz="1.68924"
				u="0.445184" v="0.126113">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="1.77132" y="-3.70053" z="0.331325"
				r="1" g="1" b="1" a="1"
				nx="0.43912" ny="-0.692855" nz="0.571949"
				u="0.45951" v="0.0943043">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="1.88653" y="-3.45654" z="0.387327"
				r="1" g="1" b="1" a="1"
				nx="0.913012" ny="-0.81884" nz="1.68924"
				u="0.472929" v="0.126113">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="1.54347" y="-3.47936" z="0.415507"
				r="1" g="1" b="1" a="1"
				nx="-0.396582" ny="0.338608" nz="0.853269"
				u="0.499164" v="0.0934603">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="1.77132" y="-3.70053" z="0.331325"
				r="1" g="1" b="1" a="1"
				nx="0.43912" ny="-0.692855" nz="0.571949"
				u="0.458604" v="0.0943043">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="1.96727" y="-3.55357" z="0.205041"
				r="1" g="1" b="1" a="1"
				nx="2.03801" ny="-1.69319" nz="-0.019731"
				u="0.472284" v="0.125721">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="1.77132" y="-3.70053" z="0.331325"
				r="1" g="1" b="1" a="1"
				nx="0.43912" ny="-0.692855" nz="0.571949"
				u="0.45951" v="0.0943043">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="1.7248" y="-3.69728" z="0.00614309"
				r="1" g="1" b="1" a="1"
				nx="0.329793" ny="-0.523339" nz="-0.785718"
				u="0.499164" v="0.0934603">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="1.96727" y="-3.55357" z="0.205041"
				r="1" g="1" b="1" a="1"
				nx="2.03801" ny="-1.69319" nz="-0.019731"
				u="0.472284" v="0.125721">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="1.7248" y="-3.69728" z="0.00614309"
				r="1" g="1" b="1" a="1"
				nx="0.329793" ny="-0.523339" nz="-0.785718"
				u="0.499164" v="0.0934603">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="1.85041" y="-3.46615" z="0.0356436"
				r="1" g="1" b="1" a="1"
				nx="1.10127" ny="-0.470536" nz="-1.00258"
				u="0.499948" v="0.126051">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="1.85041" y="-3.46615" z="0.0356436"
				r="1" g="1" b="1" a="1"
				nx="1.10127" ny="-0.470536" nz="-1.00258"
				u="0.417747" v="0.125898">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="1.7248" y="-3.69728" z="0.00614309"
				r="1" g="1" b="1" a="1"
				nx="0.329793" ny="-0.523339" nz="-0.785718"
				u="0.419236" v="0.0934196">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="1.52804" y="-3.33737" z="0.0302405"
				r="1" g="1" b="1" a="1"
				nx="-0.385334" ny="0.732827" nz="-0.560787"
				u="0.375504" v="0.118775">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="1.54347" y="-3.47936" z="0.415507"
				r="1" g="1" b="1" a="1"
				nx="-0.396582" ny="0.338608" nz="0.853269"
				u="0.419236" v="0.0934196">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="1.52804" y="-3.33737" z="0.0302405"
				r="1" g="1" b="1" a="1"
				nx="-0.385334" ny="0.732827" nz="-0.560787"
				u="0.375504" v="0.118775">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="1.3494" y="-3.60423" z="0.0931702"
				r="1" g="1" b="1" a="1"
				nx="-0.911267" ny="0.0148412" nz="-0.411548"
				u="0.372839" v="0.0785726">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="1.54347" y="-3.47936" z="0.415507"
				r="1" g="1" b="1" a="1"
				nx="-0.396582" ny="0.338608" nz="0.853269"
				u="0.419236" v="0.0934196">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="1.3494" y="-3.60423" z="0.0931702"
				r="1" g="1" b="1" a="1"
				nx="-0.911267" ny="0.0148412" nz="-0.411548"
				u="0.372839" v="0.0785726">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="1.43396" y="-3.64688" z="0.384171"
				r="1" g="1" b="1" a="1"
				nx="-0.599424" ny="-0.143499" nz="0.787464"
				u="0.40964" v="0.0704919">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="1.54347" y="-3.47936" z="0.415507"
				r="1" g="1" b="1" a="1"
				nx="-0.396582" ny="0.338608" nz="0.853269"
				u="0.499164" v="0.0934603">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="1.43396" y="-3.64688" z="0.384171"
				r="1" g="1" b="1" a="1"
				nx="-0.599424" ny="-0.143499" nz="0.787464"
				u="0.494854" v="0.0690871">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="1.59396" y="-3.80578" z="0.295766"
				r="1" g="1" b="1" a="1"
				nx="0.144779" ny="-0.861715" nz="0.486299"
				u="0.467854" v="0.0693954">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="1.54347" y="-3.47936" z="0.415507"
				r="1" g="1" b="1" a="1"
				nx="-0.396582" ny="0.338608" nz="0.853269"
				u="0.499164" v="0.0934603">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="1.59396" y="-3.80578" z="0.295766"
				r="1" g="1" b="1" a="1"
				nx="0.144779" ny="-0.861715" nz="0.486299"
				u="0.467854" v="0.0693954">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="1.77132" y="-3.70053" z="0.331325"
				r="1" g="1" b="1" a="1"
				nx="0.43912" ny="-0.692855" nz="0.571949"
				u="0.458604" v="0.0943043">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="1.7248" y="-3.69728" z="0.00614309"
				r="1" g="1" b="1" a="1"
				nx="0.329793" ny="-0.523339" nz="-0.785718"
				u="0.499164" v="0.0934603">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="1.59396" y="-3.80578" z="0.295766"
				r="1" g="1" b="1" a="1"
				nx="0.144779" ny="-0.861715" nz="0.486299"
				u="0.467854" v="0.0693954">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="1.57218" y="-3.81299" z="0.0721393"
				r="1" g="1" b="1" a="1"
				nx="-0.0312144" ny="-0.836418" nz="-0.547202"
				u="0.494854" v="0.0690871">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="1.77132" y="-3.70053" z="0.331325"
				r="1" g="1" b="1" a="1"
				nx="0.43912" ny="-0.692855" nz="0.571949"
				u="0.45951" v="0.0943043">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="1.59396" y="-3.80578" z="0.295766"
				r="1" g="1" b="1" a="1"
				nx="0.144779" ny="-0.861715" nz="0.486299"
				u="0.467854" v="0.0693954">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="1.7248" y="-3.69728" z="0.00614309"
				r="1" g="1" b="1" a="1"
				nx="0.329793" ny="-0.523339" nz="-0.785718"
				u="0.499164" v="0.0934603">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="1.52804" y="-3.33737" z="0.0302405"
				r="1" g="1" b="1" a="1"
				nx="-0.385334" ny="0.732827" nz="-0.560787"
				u="0.375504" v="0.118775">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="1.7248" y="-3.69728" z="0.00614309"
				r="1" g="1" b="1" a="1"
				nx="0.329793" ny="-0.523339" nz="-0.785718"
				u="0.419236" v="0.0934196">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="1.3494" y="-3.60423" z="0.0931702"
				r="1" g="1" b="1" a="1"
				nx="-0.911267" ny="0.0148412" nz="-0.411548"
				u="0.372839" v="0.0785726">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="1.7248" y="-3.69728" z="0.00614309"
				r="1" g="1" b="1" a="1"
				nx="0.329793" ny="-0.523339" nz="-0.785718"
				u="0.419236" v="0.0934196">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="1.57218" y="-3.81299" z="0.0721393"
				r="1" g="1" b="1" a="1"
				nx="-0.0312144" ny="-0.836418" nz="-0.547202"
				u="0.40964" v="0.0704919">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="1.3494" y="-3.60423" z="0.0931702"
				r="1" g="1" b="1" a="1"
				nx="-0.911267" ny="0.0148412" nz="-0.411548"
				u="0.372839" v="0.0785726">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="1.3494" y="-3.60423" z="0.0931702"
				r="1" g="1" b="1" a="1"
				nx="-0.911267" ny="0.0148412" nz="-0.411548"
				u="0.372839" v="0.0785726">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="1.44878" y="-3.78859" z="0.235334"
				r="1" g="1" b="1" a="1"
				nx="-0.61418" ny="-0.775063" nz="0.148529"
				u="0.391022" v="0.0532608">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="1.43396" y="-3.64688" z="0.384171"
				r="1" g="1" b="1" a="1"
				nx="-0.599424" ny="-0.143499" nz="0.787464"
				u="0.40964" v="0.0704919">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="1.43396" y="-3.64688" z="0.384171"
				r="1" g="1" b="1" a="1"
				nx="-0.599424" ny="-0.143499" nz="0.787464"
				u="0.494854" v="0.0690871">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="1.44878" y="-3.78859" z="0.235334"
				r="1" g="1" b="1" a="1"
				nx="-0.61418" ny="-0.775063" nz="0.148529"
				u="0.475839" v="0.052379">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="1.59396" y="-3.80578" z="0.295766"
				r="1" g="1" b="1" a="1"
				nx="0.144779" ny="-0.861715" nz="0.486299"
				u="0.467854" v="0.0693954">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="1.59396" y="-3.80578" z="0.295766"
				r="1" g="1" b="1" a="1"
				nx="0.144779" ny="-0.861715" nz="0.486299"
				u="0.467854" v="0.0693954">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="1.44878" y="-3.78859" z="0.235334"
				r="1" g="1" b="1" a="1"
				nx="-0.61418" ny="-0.775063" nz="0.148529"
				u="0.475839" v="0.052379">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="1.57218" y="-3.81299" z="0.0721393"
				r="1" g="1" b="1" a="1"
				nx="-0.0312144" ny="-0.836418" nz="-0.547202"
				u="0.494854" v="0.0690871">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="1.57218" y="-3.81299" z="0.0721393"
				r="1" g="1" b="1" a="1"
				nx="-0.0312144" ny="-0.836418" nz="-0.547202"
				u="0.40964" v="0.0704919">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="1.44878" y="-3.78859" z="0.235334"
				r="1" g="1" b="1" a="1"
				nx="-0.61418" ny="-0.775063" nz="0.148529"
				u="0.391022" v="0.0532608">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="1.3494" y="-3.60423" z="0.0931702"
				r="1" g="1" b="1" a="1"
				nx="-0.911267" ny="0.0148412" nz="-0.411548"
				u="0.372839" v="0.0785726">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="1.96727" y="-3.55357" z="0.205041"
				r="1" g="1" b="1" a="1"
				nx="2.03801" ny="-1.69319" nz="-0.019731"
				u="0.472284" v="0.125721">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="1.85041" y="-3.46615" z="0.0356436"
				r="1" g="1" b="1" a="1"
				nx="1.10127" ny="-0.470536" nz="-1.00258"
				u="0.47975" v="0.152229">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="1.7271" y="-3.31796" z="0.314029"
				r="1" g="1" b="1" a="1"
				nx="-0.760194" ny="1.15064" nz="0.454535"
				u="0.438064" v="0.152854">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="1.7271" y="-3.31796" z="0.314029"
				r="1" g="1" b="1" a="1"
				nx="-0.760194" ny="1.15064" nz="0.454535"
				u="0.438064" v="0.152854">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="1.85041" y="-3.46615" z="0.0356436"
				r="1" g="1" b="1" a="1"
				nx="1.10127" ny="-0.470536" nz="-1.00258"
				u="0.47975" v="0.152229">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="1.52804" y="-3.33737" z="0.0302405"
				r="1" g="1" b="1" a="1"
				nx="-0.385334" ny="0.732827" nz="-0.560787"
				u="0.459467" v="0.189855">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="1.88653" y="-3.45654" z="0.387327"
				r="1" g="1" b="1" a="1"
				nx="0.913012" ny="-0.81884" nz="1.68924"
				u="0.445184" v="0.126113">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="1.96727" y="-3.55357" z="0.205041"
				r="1" g="1" b="1" a="1"
				nx="2.03801" ny="-1.69319" nz="-0.019731"
				u="0.472284" v="0.125721">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="1.7271" y="-3.31796" z="0.314029"
				r="1" g="1" b="1" a="1"
				nx="-0.760194" ny="1.15064" nz="0.454535"
				u="0.438064" v="0.152854">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="1.7271" y="-3.31796" z="0.314029"
				r="1" g="1" b="1" a="1"
				nx="-0.760194" ny="1.15064" nz="0.454535"
				u="0.499948" v="0.126051">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="1.54347" y="-3.47936" z="0.415507"
				r="1" g="1" b="1" a="1"
				nx="-0.396582" ny="0.338608" nz="0.853269"
				u="0.499164" v="0.0934603">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="1.88653" y="-3.45654" z="0.387327"
				r="1" g="1" b="1" a="1"
				nx="0.913012" ny="-0.81884" nz="1.68924"
				u="0.472929" v="0.126113">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="2.05967" y="-3.33523" z="0.216306"
				r="1" g="1" b="1" a="1"
				nx="0.833084" ny="0.540349" nz="0.118297"
				u="0.341153" v="0.142095">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="1.9536" y="-3.38031" z="0.00561619"
				r="1" g="1" b="1" a="1"
				nx="0.967796" ny="0.922567" nz="-0.684639"
				u="0.324717" v="0.117516">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="1.83813" y="-3.24438" z="0.197887"
				r="1" g="1" b="1" a="1"
				nx="0.395173" ny="2.0712" nz="0.800317"
				u="0.357004" v="0.117135">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="2.05967" y="-3.33523" z="0.216306"
				r="1" g="1" b="1" a="1"
				nx="0.833084" ny="0.540349" nz="0.118297"
				u="0.340163" v="0.0594967">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="1.83813" y="-3.24438" z="0.197887"
				r="1" g="1" b="1" a="1"
				nx="0.395173" ny="2.0712" nz="0.800317"
				u="0.367573" v="0.0484075">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="1.97147" y="-3.38127" z="0.339565"
				r="1" g="1" b="1" a="1"
				nx="0.254334" ny="1.42294" nz="1.13547"
				u="0.353251" v="0.0739556">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="1.83813" y="-3.24438" z="0.197887"
				r="1" g="1" b="1" a="1"
				nx="0.395173" ny="2.0712" nz="0.800317"
				u="0.367573" v="0.0484075">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="1.77077" y="-3.35224" z="0.272655"
				r="1" g="1" b="1" a="1"
				nx="-0.227493" ny="0.879543" nz="1.06391"
				u="0.37744" v="0.0636555">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="1.97147" y="-3.38127" z="0.339565"
				r="1" g="1" b="1" a="1"
				nx="0.254334" ny="1.42294" nz="1.13547"
				u="0.353251" v="0.0739556">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="2.05967" y="-3.33523" z="0.216306"
				r="1" g="1" b="1" a="1"
				nx="0.833084" ny="0.540349" nz="0.118297"
				u="0.340163" v="0.0594967">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="2.06423" y="-3.49047" z="0.185104"
				r="1" g="1" b="1" a="1"
				nx="1.09236" ny="0.14901" nz="-0.581844"
				u="0.353251" v="0.0739556">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="1.9536" y="-3.38031" z="0.00561619"
				r="1" g="1" b="1" a="1"
				nx="0.967796" ny="0.922567" nz="-0.684639"
				u="0.367573" v="0.0484075">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="1.9536" y="-3.38031" z="0.00561619"
				r="1" g="1" b="1" a="1"
				nx="0.967796" ny="0.922567" nz="-0.684639"
				u="0.324717" v="0.117516">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="1.91139" y="-3.51779" z="0.0384989"
				r="1" g="1" b="1" a="1"
				nx="-1.12024" ny="0.156508" nz="-0.783399"
				u="0.32099" v="0.0997404">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="1.77077" y="-3.35224" z="0.272655"
				r="1" g="1" b="1" a="1"
				nx="-0.227493" ny="0.879543" nz="1.06391"
				u="0.36031" v="0.0992758">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="1.9536" y="-3.38031" z="0.00561619"
				r="1" g="1" b="1" a="1"
				nx="0.967796" ny="0.922567" nz="-0.684639"
				u="0.324717" v="0.117516">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="1.77077" y="-3.35224" z="0.272655"
				r="1" g="1" b="1" a="1"
				nx="-0.227493" ny="0.879543" nz="1.06391"
				u="0.36031" v="0.0992758">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="1.83813" y="-3.24438" z="0.197887"
				r="1" g="1" b="1" a="1"
				nx="0.395173" ny="2.0712" nz="0.800317"
				u="0.357004" v="0.117135">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="2.06423" y="-3.49047" z="0.185104"
				r="1" g="1" b="1" a="1"
				nx="1.09236" ny="0.14901" nz="-0.581844"
				u="0.327381" v="0.0742385">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="1.97147" y="-3.38127" z="0.339565"
				r="1" g="1" b="1" a="1"
				nx="0.254334" ny="1.42294" nz="1.13547"
				u="0.353251" v="0.0739556">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="1.77077" y="-3.35224" z="0.272655"
				r="1" g="1" b="1" a="1"
				nx="-0.227493" ny="0.879543" nz="1.06391"
				u="0.36031" v="0.0992758">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="1.91139" y="-3.51779" z="0.0384989"
				r="1" g="1" b="1" a="1"
				nx="-1.12024" ny="0.156508" nz="-0.783399"
				u="0.32099" v="0.0997404">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="2.06423" y="-3.49047" z="0.185104"
				r="1" g="1" b="1" a="1"
				nx="1.09236" ny="0.14901" nz="-0.581844"
				u="0.327381" v="0.0742385">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="1.77077" y="-3.35224" z="0.272655"
				r="1" g="1" b="1" a="1"
				nx="-0.227493" ny="0.879543" nz="1.06391"
				u="0.36031" v="0.0992758">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="1.9536" y="-3.38031" z="0.00561619"
				r="1" g="1" b="1" a="1"
				nx="0.967796" ny="0.922567" nz="-0.684639"
				u="0.367573" v="0.0484075">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="2.06423" y="-3.49047" z="0.185104"
				r="1" g="1" b="1" a="1"
				nx="1.09236" ny="0.14901" nz="-0.581844"
				u="0.353251" v="0.0739556">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="1.91139" y="-3.51779" z="0.0384989"
				r="1" g="1" b="1" a="1"
				nx="-1.12024" ny="0.156508" nz="-0.783399"
				u="0.37744" v="0.0636555">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="2.05967" y="-3.33523" z="0.216306"
				r="1" g="1" b="1" a="1"
				nx="0.833084" ny="0.540349" nz="0.118297"
				u="0.340163" v="0.0594967">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="1.97147" y="-3.38127" z="0.339565"
				r="1" g="1" b="1" a="1"
				nx="0.254334" ny="1.42294" nz="1.13547"
				u="0.353251" v="0.0739556">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="2.06423" y="-3.49047" z="0.185104"
				r="1" g="1" b="1" a="1"
				nx="1.09236" ny="0.14901" nz="-0.581844"
				u="0.327381" v="0.0742385">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="-2.90309" y="-2.1616" z="0.0360842"
				r="1" g="1" b="1" a="1"
				nx="-0.344678" ny="0.353667" nz="0.86955"
				u="0.773566" v="0.137283">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="-1.78859" y="-3.01635" z="0.0032177"
				r="1" g="1" b="1" a="1"
				nx="0.312925" ny="0.0862951" nz="0.945849"
				u="0.779302" v="0.0256778">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="-2.85836" y="-2.08917" z="0.00343466"
				r="1" g="1" b="1" a="1"
				nx="0.0351486" ny="0.392586" nz="0.919044"
				u="0.779666" v="0.13738">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="-2.99743" y="-2.25367" z="0.00332451"
				r="1" g="1" b="1" a="1"
				nx="-0.264001" ny="-0.071741" nz="0.961851"
				u="0.763465" v="0.140317">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="-2.90309" y="-2.1616" z="0.0360842"
				r="1" g="1" b="1" a="1"
				nx="-0.344678" ny="0.353667" nz="0.86955"
				u="0.773566" v="0.137283">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="-2.85836" y="-2.08917" z="0.00343466"
				r="1" g="1" b="1" a="1"
				nx="0.0351486" ny="0.392586" nz="0.919044"
				u="0.779717" v="0.140604">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="-1.8663" y="-3.24288" z="0.00303888"
				r="1" g="1" b="1" a="1"
				nx="-0.0532324" ny="-0.311961" nz="0.948603"
				u="0.760598" v="0.017829">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="-2.90309" y="-2.1616" z="0.0360842"
				r="1" g="1" b="1" a="1"
				nx="-0.344678" ny="0.353667" nz="0.86955"
				u="0.773566" v="0.137283">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="-2.99743" y="-2.25367" z="0.00332451"
				r="1" g="1" b="1" a="1"
				nx="-0.264001" ny="-0.071741" nz="0.961851"
				u="0.763414" v="0.137565">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="-1.8663" y="-3.24288" z="0.00303888"
				r="1" g="1" b="1" a="1"
				nx="-0.0532324" ny="-0.311961" nz="0.948603"
				u="0.760598" v="0.017829">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="-1.87062" y="-3.08935" z="0.0366883"
				r="1" g="1" b="1" a="1"
				nx="0.185562" ny="-0.0182828" nz="0.982462"
				u="0.770203" v="0.0270029">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="-2.90309" y="-2.1616" z="0.0360842"
				r="1" g="1" b="1" a="1"
				nx="-0.344678" ny="0.353667" nz="0.86955"
				u="0.773566" v="0.137283">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="-1.8663" y="-3.24288" z="0.00303888"
				r="1" g="1" b="1" a="1"
				nx="-0.0532324" ny="-0.311961" nz="0.948603"
				u="0.760598" v="0.017829">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="-1.77382" y="-3.16193" z="0.00311995"
				r="1" g="1" b="1" a="1"
				nx="0.784448" ny="-0.0576264" nz="0.617511"
				u="0.769884" v="0.0178343">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="-1.80014" y="-3.15268" z="0.0367293"
				r="1" g="1" b="1" a="1"
				nx="0.512902" ny="0.0732262" nz="0.855318"
				u="0.769954" v="0.0199868">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="-1.84733" y="-3.09936" z="0.00307941"
				r="1" g="1" b="1" a="1"
				nx="0.82645" ny="0.276182" nz="0.490616"
				u="0.769884" v="0.0178343">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="-1.78859" y="-3.01635" z="0.0032177"
				r="1" g="1" b="1" a="1"
				nx="0.312925" ny="0.0862951" nz="0.945849"
				u="0.779169" v="0.0178396">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="-1.87062" y="-3.08935" z="0.0366883"
				r="1" g="1" b="1" a="1"
				nx="0.185562" ny="-0.0182828" nz="0.982462"
				u="0.769954" v="0.0199868">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="-1.8663" y="-3.24288" z="0.00303888"
				r="1" g="1" b="1" a="1"
				nx="-0.0532324" ny="-0.311961" nz="0.948603"
				u="0.760598" v="0.017829">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="-1.80014" y="-3.15268" z="0.0367293"
				r="1" g="1" b="1" a="1"
				nx="0.512902" ny="0.0732262" nz="0.855318"
				u="0.769954" v="0.0199868">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="-1.87062" y="-3.08935" z="0.0366883"
				r="1" g="1" b="1" a="1"
				nx="0.185562" ny="-0.0182828" nz="0.982462"
				u="0.770203" v="0.0270029">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="-2.90309" y="-2.1616" z="0.0360842"
				r="1" g="1" b="1" a="1"
				nx="-0.344678" ny="0.353667" nz="0.86955"
				u="0.773566" v="0.137283">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="-1.87062" y="-3.08935" z="0.0366883"
				r="1" g="1" b="1" a="1"
				nx="0.185562" ny="-0.0182828" nz="0.982462"
				u="0.770203" v="0.0270029">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="-1.78859" y="-3.01635" z="0.0032177"
				r="1" g="1" b="1" a="1"
				nx="0.312925" ny="0.0862951" nz="0.945849"
				u="0.779302" v="0.0256778">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="-1.87062" y="-3.08935" z="0.0366883"
				r="1" g="1" b="1" a="1"
				nx="0.185562" ny="-0.0182828" nz="0.982462"
				u="0.770203" v="0.0270029">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="-1.77382" y="-3.16193" z="0.00311995"
				r="1" g="1" b="1" a="1"
				nx="0.784448" ny="-0.0576264" nz="0.617511"
				u="0.773479" v="0.0191655">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="-1.84733" y="-3.09936" z="0.00307941"
				r="1" g="1" b="1" a="1"
				nx="0.82645" ny="0.276182" nz="0.490616"
				u="0.773505" v="0.026522">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="-1.80014" y="-3.15268" z="0.0367293"
				r="1" g="1" b="1" a="1"
				nx="0.512902" ny="0.0732262" nz="0.855318"
				u="0.769954" v="0.0199868">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="-1.77382" y="-3.16193" z="0.00311995"
				r="1" g="1" b="1" a="1"
				nx="0.784448" ny="-0.0576264" nz="0.617511"
				u="0.773479" v="0.0191655">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="-1.87062" y="-3.08935" z="0.0366883"
				r="1" g="1" b="1" a="1"
				nx="0.185562" ny="-0.0182828" nz="0.982462"
				u="0.770203" v="0.0270029">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="-2.14686" y="-2.00406" z="0.0371633"
				r="1" g="1" b="1" a="1"
				nx="-0.00702246" ny="-0.00436536" nz="0.999966"
				u="0.635034" v="0.500004">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="-1.31508" y="-3.02689" z="0.0385394"
				r="1" g="1" b="1" a="1"
				nx="-0.00978447" ny="-0.00630162" nz="0.999932"
				u="0.640419" v="0.618816">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="-2.07464" y="-1.94341" z="0.0379353"
				r="1" g="1" b="1" a="1"
				nx="-0.00716115" ny="-0.00446258" nz="0.999964"
				u="0.627053" v="0.500003">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>