<?xml version="1.0" encoding="UTF-8" standalone="yes"?>

<!DOCTYPE mesh [
	<!ELEMENT mesh       (polygons, skeleton?)>
	<!ELEMENT polygons   (polygon+)>
	<!ELEMENT polygon    (vertex, vertex, vertex)>
	<!ELEMENT vertex     (skin+)>
	<!ELEMENT skin        EMPTY>
	<!ELEMENT skeleton   (bones, init_pose)>
	<!ELEMENT bones      (bone+)>
	<!ELEMENT init_pose  (transform+)>
	<!ELEMENT bone        EMPTY>
	<!ELEMENT transform   EMPTY>
	<!ATTLIST mesh texture CDATA #IMPLIED>
	<!ATTLIST vertex x CDATA #REQUIRED>
	<!ATTLIST vertex y CDATA #REQUIRED>
	<!ATTLIST vertex z CDATA #REQUIRED>
	<!ATTLIST vertex r CDATA #REQUIRED>
	<!ATTLIST vertex g CDATA #REQUIRED>
	<!ATTLIST vertex b CDATA #REQUIRED>
	<!ATTLIST vertex a CDATA #REQUIRED>
	<!ATTLIST vertex nx CDATA #REQUIRED>
	<!ATTLIST vertex ny CDATA #REQUIRED>
	<!ATTLIST vertex nz CDATA #REQUIRED>
	<!ATTLIST vertex u CDATA #REQUIRED>
	<!ATTLIST vertex v CDATA #REQUIRED>
	<!ATTLIST vertex u2 CDATA #IMPLIED>
	<!ATTLIST vertex v2 CDATA #IMPLIED>
	<!ATTLIST skin bone CDATA #REQUIRED>
	<!ATTLIST skin weight CDATA #REQUIRED>
	<!ATTLIST transform name CDATA #REQUIRED>
	<!ATTLIST transform m00 CDATA #REQUIRED>
	<!ATTLIST transform m01 CDATA #REQUIRED>
	<!ATTLIST transform m02 CDATA #REQUIRED>
	<!ATTLIST transform m03 CDATA #REQUIRED>
	<!ATTLIST transform m10 CDATA #REQUIRED>
	<!ATTLIST transform m11 CDATA #REQUIRED>
	<!ATTLIST transform m12 CDATA #REQUIRED>
	<!ATTLIST transform m13 CDATA #REQUIRED>
	<!ATTLIST transform m20 CDATA #REQUIRED>
	<!ATTLIST transform m21 CDATA #REQUIRED>
	<!ATTLIST transform m22 CDATA #REQUIRED>
	<!ATTLIST transform m23 CDATA #REQUIRED>
	<!ATTLIST transform m30 CDATA #REQUIRED>
	<!ATTLIST transform m31 CDATA #REQUIRED>
	<!ATTLIST transform m32 CDATA #REQUIRED>
	<!ATTLIST transform m33 CDATA #REQUIRED>
	<!ATTLIST bone name CDATA #REQUIRED>
	<!ATTLIST bone parent CDATA #REQUIRED>
]>

<mesh texture="viking_warrior_rock,viking_warrior_iron,viking_warrior_rubber">
	<polygons>
		<polygon>
			<vertex x="-0.224353" y="0.140702" z="1.3751" r="1" g="1" b="1" a="1" nx="-0.713546" ny="0.564497" nz="0.414965" u="0.167296" v="0.733282">
				<skin bone="warrior  Spine1" weight="1"/>
				<skin bone="warrior  R UpperArm" weight="0"/>
				<skin bone="warrior  Head" weight="0"/>
			</vertex>
			<vertex x="-0.543141" y="-0.0719832" z="0.648913" r="1" g="1" b="1" a="1" nx="-0.943639" ny="0.183374" nz="-0.275535" u="0.138229" v="0.667866">
				<skin bone="warrior  Pelvis" weight="1"/>
			</vertex>
			<vertex x="-0.230411" y="-0.680188" z="0.641105" r="1" g="1" b="1" a="1" nx="-0.484513" ny="-0.848776" nz="-0.211723" u="0.187362" v="0.631202">
				<skin bone="warrior  Pelvis" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="-0.224353" y="0.140702" z="1.3751" r="1" g="1" b="1" a="1" nx="-0.713546" ny="0.564497" nz="0.414965" u="0.167296" v="0.733282">
				<skin bone="warrior  Spine1" weight="1"/>
				<skin bone="warrior  R UpperArm" weight="0"/>
				<skin bone="warrior  Head" weight="0"/>
			</vertex>
			<vertex x="-0.230411" y="-0.680188" z="0.641105" r="1" g="1" b="1" a="1" nx="-0.484513" ny="-0.848776" nz="-0.211723" u="0.187362" v="0.631202">
				<skin bone="warrior  Pelvis" weight="1"/>
			</vertex>
			<vertex x="-4.80408e-05" y="-0.246138" z="1.28967" r="1" g="1" b="1" a="1" nx="-0.00184836" ny="-0.839068" nz="0.544023" u="0.207843" v="0.719831">
				<skin bone="warrior  Spine1" weight="0.99966"/>
				<skin bone="warrior  Head" weight="0.000339591"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="0.00498819" y="0.211973" z="0.631624" r="1" g="1" b="1" a="1" nx="0.00204004" ny="0.914254" nz="-0.405136" u="0.311083" v="0.741311">
				<skin bone="warrior  Pelvis" weight="1"/>
			</vertex>
			<vertex x="-0.543141" y="-0.0719832" z="0.648913" r="1" g="1" b="1" a="1" nx="-0.943639" ny="0.183374" nz="-0.275535" u="0.368351" v="0.741098">
				<skin bone="warrior  Pelvis" weight="1"/>
			</vertex>
			<vertex x="-0.224353" y="0.140702" z="1.3751" r="1" g="1" b="1" a="1" nx="-0.713546" ny="0.564497" nz="0.414965" u="0.332275" v="0.808062">
				<skin bone="warrior  Spine1" weight="1"/>
				<skin bone="warrior  R UpperArm" weight="0"/>
				<skin bone="warrior  Head" weight="0"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="-0.543141" y="-0.0719832" z="0.648913" r="1" g="1" b="1" a="1" nx="-0.943639" ny="0.183374" nz="-0.275535" u="0.153383" v="0.580175">
				<skin bone="warrior  Pelvis" weight="1"/>
			</vertex>
			<vertex x="-0.000459443" y="-0.115936" z="0.366572" r="1" g="1" b="1" a="1" nx="-0.00471369" ny="0.142933" nz="-0.989721" u="0.208099" v="0.575018">
				<skin bone="warrior  Pelvis" weight="1"/>
			</vertex>
			<vertex x="-0.230411" y="-0.680188" z="0.641105" r="1" g="1" b="1" a="1" nx="-0.484513" ny="-0.848776" nz="-0.211723" u="0.187362" v="0.631202">
				<skin bone="warrior  Pelvis" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="-4.80408e-05" y="-0.246138" z="1.28967" r="1" g="1" b="1" a="1" nx="-0.00184836" ny="-0.839068" nz="0.544023" u="0.207843" v="0.719831">
				<skin bone="warrior  Spine1" weight="0.99966"/>
				<skin bone="warrior  Head" weight="0.000339591"/>
			</vertex>
			<vertex x="0.235399" y="-0.680188" z="0.641105" r="1" g="1" b="1" a="1" nx="0.483965" ny="-0.849186" nz="-0.21133" u="0.229105" v="0.631299">
				<skin bone="warrior  Pelvis" weight="1"/>
			</vertex>
			<vertex x="0.224353" y="0.140702" z="1.3751" r="1" g="1" b="1" a="1" nx="0.710813" ny="0.564897" nz="0.41909" u="0.248138" v="0.733625">
				<skin bone="warrior  Spine1" weight="1"/>
				<skin bone="warrior  L UpperArm" weight="0"/>
				<skin bone="warrior  Head" weight="0"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="0.522976" y="-0.0337285" z="1.3499" r="1" g="1" b="1" a="1" nx="-0.343071" ny="-0.933083" nz="-0.107976" u="0.400323" v="0.767061">
				<skin bone="warrior  L UpperArm" weight="0.5"/>
				<skin bone="warrior  L Forearm" weight="0.5"/>
			</vertex>
			<vertex x="0.536114" y="0.0926801" z="1.24884" r="1" g="1" b="1" a="1" nx="-0.237192" ny="-0.247044" nz="-0.939526" u="0.398104" v="0.752701">
				<skin bone="warrior  L Forearm" weight="0.666667"/>
				<skin bone="warrior  L UpperArm" weight="0.333333"/>
			</vertex>
			<vertex x="1.12521" y="0.0964689" z="1.13584" r="1" g="1" b="1" a="1" nx="0.37633" ny="-0.71631" nz="-0.587602" u="0.450313" v="0.736291">
				<skin bone="warrior  L Forearm" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="-4.80408e-05" y="-0.246138" z="1.28967" r="1" g="1" b="1" a="1" nx="-0.00184836" ny="-0.839068" nz="0.544023" u="0.207843" v="0.719831">
				<skin bone="warrior  Spine1" weight="0.99966"/>
				<skin bone="warrior  Head" weight="0.000339591"/>
			</vertex>
			<vertex x="0.224353" y="0.140702" z="1.3751" r="1" g="1" b="1" a="1" nx="0.710813" ny="0.564897" nz="0.41909" u="0.248138" v="0.733625">
				<skin bone="warrior  Spine1" weight="1"/>
				<skin bone="warrior  L UpperArm" weight="0"/>
				<skin bone="warrior  Head" weight="0"/>
			</vertex>
			<vertex x="0" y="-0.300081" z="2.17742" r="1" g="1" b="1" a="1" nx="1.81847e-05" ny="-0.345841" nz="0.938293" u="0.207402" v="0.807615">
				<skin bone="warrior  Head" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="-4.80408e-05" y="-0.246138" z="1.28967" r="1" g="1" b="1" a="1" nx="-0.00184836" ny="-0.839068" nz="0.544023" u="0.207843" v="0.719831">
				<skin bone="warrior  Spine1" weight="0.99966"/>
				<skin bone="warrior  Head" weight="0.000339591"/>
			</vertex>
			<vertex x="-0.230411" y="-0.680188" z="0.641105" r="1" g="1" b="1" a="1" nx="-0.484513" ny="-0.848776" nz="-0.211723" u="0.187362" v="0.631202">
				<skin bone="warrior  Pelvis" weight="1"/>
			</vertex>
			<vertex x="0.235399" y="-0.680188" z="0.641105" r="1" g="1" b="1" a="1" nx="0.483965" ny="-0.849186" nz="-0.21133" u="0.229105" v="0.631299">
				<skin bone="warrior  Pelvis" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="-0.543141" y="-0.0719832" z="0.648913" r="1" g="1" b="1" a="1" nx="-0.943639" ny="0.183374" nz="-0.275535" u="0.368351" v="0.741098">
				<skin bone="warrior  Pelvis" weight="1"/>
			</vertex>
			<vertex x="0.00498819" y="0.211973" z="0.631624" r="1" g="1" b="1" a="1" nx="0.00204004" ny="0.914254" nz="-0.405136" u="0.311083" v="0.741311">
				<skin bone="warrior  Pelvis" weight="1"/>
			</vertex>
			<vertex x="-0.000459443" y="-0.115936" z="0.366572" r="1" g="1" b="1" a="1" nx="-0.00471369" ny="0.142933" nz="-0.989721" u="0.311338" v="0.703499">
				<skin bone="warrior  Pelvis" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="1.08174" y="0.0973019" z="1.59051" r="1" g="1" b="1" a="1" nx="0.471278" ny="0.108466" nz="0.87529" u="0.481197" v="0.763151">
				<skin bone="warrior  L Forearm" weight="1"/>
			</vertex>
			<vertex x="1.165" y="-0.209221" z="1.58366" r="1" g="1" b="1" a="1" nx="0.540195" ny="-0.718767" nz="0.437681" u="0.461501" v="0.783709">
				<skin bone="warrior  L Forearm" weight="1"/>
			</vertex>
			<vertex x="1.12521" y="0.0964689" z="1.13584" r="1" g="1" b="1" a="1" nx="0.37633" ny="-0.71631" nz="-0.587602" u="0.450313" v="0.736291">
				<skin bone="warrior  L Forearm" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="0.522976" y="-0.0337285" z="1.3499" r="1" g="1" b="1" a="1" nx="-0.343071" ny="-0.933083" nz="-0.107976" u="0.400323" v="0.767061">
				<skin bone="warrior  L UpperArm" weight="0.5"/>
				<skin bone="warrior  L Forearm" weight="0.5"/>
			</vertex>
			<vertex x="1.12521" y="0.0964689" z="1.13584" r="1" g="1" b="1" a="1" nx="0.37633" ny="-0.71631" nz="-0.587602" u="0.450313" v="0.736291">
				<skin bone="warrior  L Forearm" weight="1"/>
			</vertex>
			<vertex x="1.165" y="-0.209221" z="1.58366" r="1" g="1" b="1" a="1" nx="0.540195" ny="-0.718767" nz="0.437681" u="0.461501" v="0.783709">
				<skin bone="warrior  L Forearm" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="1.08174" y="0.0973019" z="1.59051" r="1" g="1" b="1" a="1" nx="0.471278" ny="0.108466" nz="0.87529" u="0.442499" v="0.80491">
				<skin bone="warrior  L Forearm" weight="1"/>
			</vertex>
			<vertex x="0.536114" y="0.0926801" z="1.45096" r="1" g="1" b="1" a="1" nx="-0.357816" ny="-0.118382" nz="0.926258" u="0.398038" v="0.781426">
				<skin bone="warrior  L UpperArm" weight="0.333333"/>
				<skin bone="warrior  L Forearm" weight="0.666667"/>
			</vertex>
			<vertex x="1.165" y="-0.209221" z="1.58366" r="1" g="1" b="1" a="1" nx="0.540195" ny="-0.718767" nz="0.437681" u="0.461501" v="0.783709">
				<skin bone="warrior  L Forearm" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="-0.890975" y="-0.0908025" z="2.24755" r="1" g="1" b="1" a="1" nx="0.123706" ny="-0.991367" nz="-0.0434542" u="0.10032" v="0.744861">
				<skin bone="warrior  Prop1" weight="1"/>
			</vertex>
			<vertex x="-1.41375" y="-0.155441" z="2.23398" r="1" g="1" b="1" a="1" nx="0.123706" ny="-0.991367" nz="-0.0434542" u="0.14754" v="0.744861">
				<skin bone="warrior  Prop1" weight="1"/>
			</vertex>
			<vertex x="-0.867312" y="-0.0364223" z="1.07428" r="1" g="1" b="1" a="1" nx="0.123706" ny="-0.991367" nz="-0.0434542" u="0.100331" v="0.639586">
				<skin bone="warrior  Prop1" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="-0.890975" y="-0.0908025" z="2.24755" r="1" g="1" b="1" a="1" nx="-0.123706" ny="0.991367" nz="0.0434542" u="0.10032" v="0.744861">
				<skin bone="warrior  Prop1" weight="1"/>
			</vertex>
			<vertex x="-0.867312" y="-0.0364223" z="1.07428" r="1" g="1" b="1" a="1" nx="-0.123706" ny="0.991367" nz="0.0434542" u="0.100331" v="0.639586">
				<skin bone="warrior  Prop1" weight="1"/>
			</vertex>
			<vertex x="-1.41375" y="-0.155441" z="2.23398" r="1" g="1" b="1" a="1" nx="-0.123706" ny="0.991367" nz="0.0434542" u="0.14754" v="0.744861">
				<skin bone="warrior  Prop1" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="0.508635" y="0.0949147" z="1.85348" r="1" g="1" b="1" a="1" nx="-0.0168829" ny="0.999857" nz="0" u="0.388435" v="0.984949">
				<skin bone="warrior  L Forearm" weight="1"/>
				<skin bone="warrior  R UpperArm" weight="0"/>
			</vertex>
			<vertex x="1.40951" y="0.110126" z="0.940323" r="1" g="1" b="1" a="1" nx="-0.0168829" ny="0.999857" nz="0" u="0.307693" v="0.903118">
				<skin bone="warrior  L Forearm" weight="1"/>
			</vertex>
			<vertex x="0.508635" y="0.0949149" z="0.940656" r="1" g="1" b="1" a="1" nx="-0.0168828" ny="0.999857" nz="1.55058e-07" u="0.388435" v="0.903148">
				<skin bone="warrior  L Forearm" weight="1"/>
				<skin bone="warrior  R UpperArm" weight="0"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="1.40951" y="0.110126" z="1.85222" r="1" g="1" b="1" a="1" nx="-0.0168829" ny="0.999857" nz="0" u="0.307693" v="0.984837">
				<skin bone="warrior  L Forearm" weight="1"/>
			</vertex>
			<vertex x="1.40951" y="0.110126" z="0.940323" r="1" g="1" b="1" a="1" nx="-0.0168829" ny="0.999857" nz="0" u="0.307693" v="0.903118">
				<skin bone="warrior  L Forearm" weight="1"/>
			</vertex>
			<vertex x="0.508635" y="0.0949147" z="1.85348" r="1" g="1" b="1" a="1" nx="-0.0168829" ny="0.999857" nz="0" u="0.388435" v="0.984949">
				<skin bone="warrior  L Forearm" weight="1"/>
				<skin bone="warrior  R UpperArm" weight="0"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="1.40951" y="0.110126" z="0.940323" r="1" g="1" b="1" a="1" nx="0.0168829" ny="-0.999857" nz="0" u="0.297424" v="0.903265">
				<skin bone="warrior  L Forearm" weight="1"/>
			</vertex>
			<vertex x="0.508635" y="0.0949147" z="1.85348" r="1" g="1" b="1" a="1" nx="0.0168829" ny="-0.999857" nz="0" u="0.216682" v="0.985096">
				<skin bone="warrior  L Forearm" weight="1"/>
				<skin bone="warrior  R UpperArm" weight="0"/>
			</vertex>
			<vertex x="0.508635" y="0.0949149" z="0.940656" r="1" g="1" b="1" a="1" nx="0.0168828" ny="-0.999857" nz="-1.55058e-07" u="0.216682" v="0.903295">
				<skin bone="warrior  L Forearm" weight="1"/>
				<skin bone="warrior  R UpperArm" weight="0"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="1.40951" y="0.110126" z="1.85222" r="1" g="1" b="1" a="1" nx="0.0168829" ny="-0.999857" nz="0" u="0.297424" v="0.984983">
				<skin bone="warrior  L Forearm" weight="1"/>
			</vertex>
			<vertex x="0.508635" y="0.0949147" z="1.85348" r="1" g="1" b="1" a="1" nx="0.0168829" ny="-0.999857" nz="0" u="0.216682" v="0.985096">
				<skin bone="warrior  L Forearm" weight="1"/>
				<skin bone="warrior  R UpperArm" weight="0"/>
			</vertex>
			<vertex x="1.40951" y="0.110126" z="0.940323" r="1" g="1" b="1" a="1" nx="0.0168829" ny="-0.999857" nz="0" u="0.297424" v="0.903265">
				<skin bone="warrior  L Forearm" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="0" y="-0.300081" z="2.17742" r="1" g="1" b="1" a="1" nx="1.81847e-05" ny="-0.345841" nz="0.938293" u="0.312944" v="0.890283">
				<skin bone="warrior  Head" weight="1"/>
			</vertex>
			<vertex x="0.224353" y="0.140702" z="1.3751" r="1" g="1" b="1" a="1" nx="0.710813" ny="0.564897" nz="0.41909" u="0.292067" v="0.808441">
				<skin bone="warrior  Spine1" weight="1"/>
				<skin bone="warrior  L UpperArm" weight="0"/>
				<skin bone="warrior  Head" weight="0"/>
			</vertex>
			<vertex x="-0.224353" y="0.140702" z="1.3751" r="1" g="1" b="1" a="1" nx="-0.713546" ny="0.564497" nz="0.414965" u="0.332275" v="0.808062">
				<skin bone="warrior  Spine1" weight="1"/>
				<skin bone="warrior  R UpperArm" weight="0"/>
				<skin bone="warrior  Head" weight="0"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="0" y="-0.300081" z="2.17742" r="1" g="1" b="1" a="1" nx="1.81847e-05" ny="-0.345841" nz="0.938293" u="0.207402" v="0.807615">
				<skin bone="warrior  Head" weight="1"/>
			</vertex>
			<vertex x="-0.224353" y="0.140702" z="1.3751" r="1" g="1" b="1" a="1" nx="-0.713546" ny="0.564497" nz="0.414965" u="0.167296" v="0.733282">
				<skin bone="warrior  Spine1" weight="1"/>
				<skin bone="warrior  R UpperArm" weight="0"/>
				<skin bone="warrior  Head" weight="0"/>
			</vertex>
			<vertex x="-4.80408e-05" y="-0.246138" z="1.28967" r="1" g="1" b="1" a="1" nx="-0.00184836" ny="-0.839068" nz="0.544023" u="0.207843" v="0.719831">
				<skin bone="warrior  Spine1" weight="0.99966"/>
				<skin bone="warrior  Head" weight="0.000339591"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="0.235399" y="-0.680188" z="0.641105" r="1" g="1" b="1" a="1" nx="0.483965" ny="-0.849186" nz="-0.21133" u="0.229105" v="0.631299">
				<skin bone="warrior  Pelvis" weight="1"/>
			</vertex>
			<vertex x="-0.000459443" y="-0.115936" z="0.366572" r="1" g="1" b="1" a="1" nx="-0.00471369" ny="0.142933" nz="-0.989721" u="0.208099" v="0.575018">
				<skin bone="warrior  Pelvis" weight="1"/>
			</vertex>
			<vertex x="0.553117" y="-0.0719834" z="0.648913" r="1" g="1" b="1" a="1" nx="0.944932" ny="0.180465" nz="-0.273014" u="0.263663" v="0.580413">
				<skin bone="warrior  Pelvis" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="0.235399" y="-0.680188" z="0.641105" r="1" g="1" b="1" a="1" nx="0.483965" ny="-0.849186" nz="-0.21133" u="0.229105" v="0.631299">
				<skin bone="warrior  Pelvis" weight="1"/>
			</vertex>
			<vertex x="0.553117" y="-0.0719834" z="0.648913" r="1" g="1" b="1" a="1" nx="0.944932" ny="0.180465" nz="-0.273014" u="0.278263" v="0.668273">
				<skin bone="warrior  Pelvis" weight="1"/>
			</vertex>
			<vertex x="0.224353" y="0.140702" z="1.3751" r="1" g="1" b="1" a="1" nx="0.710813" ny="0.564897" nz="0.41909" u="0.248138" v="0.733625">
				<skin bone="warrior  Spine1" weight="1"/>
				<skin bone="warrior  L UpperArm" weight="0"/>
				<skin bone="warrior  Head" weight="0"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="-0.230411" y="-0.680188" z="0.641105" r="1" g="1" b="1" a="1" nx="-0.484513" ny="-0.848776" nz="-0.211723" u="0.187362" v="0.631202">
				<skin bone="warrior  Pelvis" weight="1"/>
			</vertex>
			<vertex x="-0.000459443" y="-0.115936" z="0.366572" r="1" g="1" b="1" a="1" nx="-0.00471369" ny="0.142933" nz="-0.989721" u="0.208099" v="0.575018">
				<skin bone="warrior  Pelvis" weight="1"/>
			</vertex>
			<vertex x="0.235399" y="-0.680188" z="0.641105" r="1" g="1" b="1" a="1" nx="0.483965" ny="-0.849186" nz="-0.21133" u="0.229105" v="0.631299">
				<skin bone="warrior  Pelvis" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="0.224353" y="0.140702" z="1.3751" r="1" g="1" b="1" a="1" nx="0.710813" ny="0.564897" nz="0.41909" u="0.292067" v="0.808441">
				<skin bone="warrior  Spine1" weight="1"/>
				<skin bone="warrior  L UpperArm" weight="0"/>
				<skin bone="warrior  Head" weight="0"/>
			</vertex>
			<vertex x="0.00498819" y="0.211973" z="0.631624" r="1" g="1" b="1" a="1" nx="0.00204004" ny="0.914254" nz="-0.405136" u="0.311083" v="0.741311">
				<skin bone="warrior  Pelvis" weight="1"/>
			</vertex>
			<vertex x="-0.224353" y="0.140702" z="1.3751" r="1" g="1" b="1" a="1" nx="-0.713546" ny="0.564497" nz="0.414965" u="0.332275" v="0.808062">
				<skin bone="warrior  Spine1" weight="1"/>
				<skin bone="warrior  R UpperArm" weight="0"/>
				<skin bone="warrior  Head" weight="0"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="0.00498819" y="0.211973" z="0.631624" r="1" g="1" b="1" a="1" nx="0.00204004" ny="0.914254" nz="-0.405136" u="0.311083" v="0.741311">
				<skin bone="warrior  Pelvis" weight="1"/>
			</vertex>
			<vertex x="0.553117" y="-0.0719834" z="0.648913" r="1" g="1" b="1" a="1" nx="0.944932" ny="0.180465" nz="-0.273014" u="0.253737" v="0.741263">
				<skin bone="warrior  Pelvis" weight="1"/>
			</vertex>
			<vertex x="-0.000459443" y="-0.115936" z="0.366572" r="1" g="1" b="1" a="1" nx="-0.00471369" ny="0.142933" nz="-0.989721" u="0.311338" v="0.703499">
				<skin bone="warrior  Pelvis" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="0.536114" y="0.0926801" z="1.45096" r="1" g="1" b="1" a="1" nx="-0.357816" ny="-0.118382" nz="0.926258" u="0.398038" v="0.781426">
				<skin bone="warrior  L UpperArm" weight="0.333333"/>
				<skin bone="warrior  L Forearm" weight="0.666667"/>
			</vertex>
			<vertex x="0.522976" y="-0.0337285" z="1.3499" r="1" g="1" b="1" a="1" nx="-0.343071" ny="-0.933083" nz="-0.107976" u="0.400323" v="0.767061">
				<skin bone="warrior  L UpperArm" weight="0.5"/>
				<skin bone="warrior  L Forearm" weight="0.5"/>
			</vertex>
			<vertex x="1.165" y="-0.209221" z="1.58366" r="1" g="1" b="1" a="1" nx="0.540195" ny="-0.718767" nz="0.437681" u="0.461501" v="0.783709">
				<skin bone="warrior  L Forearm" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="0.379907" y="-0.318733" z="2.3155" r="1" g="1" b="1" a="1" nx="1.55804e-07" ny="-0.993061" nz="-0.1176" u="0.279539" v="0.812915">
				<skin bone="warrior  Head" weight="1"/>
			</vertex>
			<vertex x="-0.379907" y="-0.318734" z="2.3155" r="1" g="1" b="1" a="1" nx="1.55804e-07" ny="-0.993061" nz="-0.1176" u="0.211449" v="0.812915">
				<skin bone="warrior  Head" weight="1"/>
			</vertex>
			<vertex x="0" y="-0.271086" z="1.91315" r="1" g="1" b="1" a="1" nx="1.55804e-07" ny="-0.993061" nz="-0.1176" u="0.245494" v="0.776606">
				<skin bone="warrior  Head" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="-0.379907" y="-0.318734" z="2.3155" r="1" g="1" b="1" a="1" nx="-1.55804e-07" ny="0.993061" nz="0.1176" u="0.211449" v="0.812915">
				<skin bone="warrior  Head" weight="1"/>
			</vertex>
			<vertex x="0.379907" y="-0.318733" z="2.3155" r="1" g="1" b="1" a="1" nx="-1.55804e-07" ny="0.993061" nz="0.1176" u="0.279539" v="0.812915">
				<skin bone="warrior  Head" weight="1"/>
			</vertex>
			<vertex x="0" y="-0.271086" z="1.91315" r="1" g="1" b="1" a="1" nx="-1.55804e-07" ny="0.993061" nz="0.1176" u="0.245494" v="0.776606">
				<skin bone="warrior  Head" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="-0.522976" y="-0.0337285" z="1.3499" r="1" g="1" b="1" a="1" nx="0.343071" ny="-0.933083" nz="-0.107975" u="0.14605" v="0.788119">
				<skin bone="warrior  R UpperArm" weight="0.333333"/>
				<skin bone="warrior  R Forearm" weight="0.666667"/>
			</vertex>
			<vertex x="-1.12521" y="0.096469" z="1.13584" r="1" g="1" b="1" a="1" nx="-0.513662" ny="0.256841" nz="-0.818648" u="0.0953926" v="0.757716">
				<skin bone="warrior  R Hand" weight="1"/>
			</vertex>
			<vertex x="-0.536114" y="0.0926801" z="1.24884" r="1" g="1" b="1" a="1" nx="0.228188" ny="0.406302" nz="-0.884788" u="0.148269" v="0.773755">
				<skin bone="warrior  R Forearm" weight="0.5"/>
				<skin bone="warrior  R UpperArm" weight="0.5"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="-0.093441" y="0.0160623" z="1.36687" r="1" g="1" b="1" a="1" nx="0.996355" ny="-0.077074" nz="0.0365648" u="0.186356" v="0.790622">
				<skin bone="warrior  Spine1" weight="0.5"/>
				<skin bone="warrior  Head" weight="0"/>
				<skin bone="warrior  R UpperArm" weight="0.5"/>
			</vertex>
			<vertex x="-0.536114" y="0.0926801" z="1.24884" r="1" g="1" b="1" a="1" nx="0.228188" ny="0.406302" nz="-0.884788" u="0.158603" v="0.823436">
				<skin bone="warrior  R Forearm" weight="0.5"/>
				<skin bone="warrior  R UpperArm" weight="0.5"/>
			</vertex>
			<vertex x="-0.536114" y="0.0926801" z="1.45096" r="1" g="1" b="1" a="1" nx="0.321336" ny="0.475185" nz="0.819111" u="0.148169" v="0.804616">
				<skin bone="warrior  R Forearm" weight="0.5"/>
				<skin bone="warrior  R UpperArm" weight="0.5"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="-0.093441" y="0.0160623" z="1.36687" r="1" g="1" b="1" a="1" nx="0.996355" ny="-0.077074" nz="0.0365648" u="0.186356" v="0.790622">
				<skin bone="warrior  Spine1" weight="0.5"/>
				<skin bone="warrior  Head" weight="0"/>
				<skin bone="warrior  R UpperArm" weight="0.5"/>
			</vertex>
			<vertex x="-0.549802" y="-0.0337285" z="1.3499" r="1" g="1" b="1" a="1" nx="0.109018" ny="-0.993918" nz="-0.0155431" u="0.14605" v="0.788119">
				<skin bone="warrior  R UpperArm" weight="0.666667"/>
				<skin bone="warrior  R Forearm" weight="0.333333"/>
			</vertex>
			<vertex x="-0.536114" y="0.0926801" z="1.24884" r="1" g="1" b="1" a="1" nx="0.228188" ny="0.406302" nz="-0.884788" u="0.148269" v="0.773755">
				<skin bone="warrior  R Forearm" weight="0.5"/>
				<skin bone="warrior  R UpperArm" weight="0.5"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="-0.093441" y="0.0160623" z="1.36687" r="1" g="1" b="1" a="1" nx="0.996355" ny="-0.077074" nz="0.0365648" u="0.186356" v="0.790622">
				<skin bone="warrior  Spine1" weight="0.5"/>
				<skin bone="warrior  Head" weight="0"/>
				<skin bone="warrior  R UpperArm" weight="0.5"/>
			</vertex>
			<vertex x="-0.536114" y="0.0926801" z="1.45096" r="1" g="1" b="1" a="1" nx="0.321336" ny="0.475185" nz="0.819111" u="0.148169" v="0.804616">
				<skin bone="warrior  R Forearm" weight="0.5"/>
				<skin bone="warrior  R UpperArm" weight="0.5"/>
			</vertex>
			<vertex x="-0.549802" y="-0.0337285" z="1.3499" r="1" g="1" b="1" a="1" nx="0.109018" ny="-0.993918" nz="-0.0155431" u="0.14605" v="0.788119">
				<skin bone="warrior  R UpperArm" weight="0.666667"/>
				<skin bone="warrior  R Forearm" weight="0.333333"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="-1.08174" y="0.0973019" z="1.59051" r="1" g="1" b="1" a="1" nx="-0.372874" ny="0.610718" nz="0.698562" u="0.0645087" v="0.784576">
				<skin bone="warrior  R Hand" weight="1"/>
			</vertex>
			<vertex x="-1.12521" y="0.096469" z="1.13584" r="1" g="1" b="1" a="1" nx="-0.513662" ny="0.256841" nz="-0.818648" u="0.0953926" v="0.757716">
				<skin bone="warrior  R Hand" weight="1"/>
			</vertex>
			<vertex x="-1.165" y="-0.209221" z="1.58366" r="1" g="1" b="1" a="1" nx="-0.540195" ny="-0.718767" nz="0.437681" u="0.0842617" v="0.805016">
				<skin bone="warrior  R Hand" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="-0.522976" y="-0.0337285" z="1.3499" r="1" g="1" b="1" a="1" nx="0.343071" ny="-0.933083" nz="-0.107975" u="0.14605" v="0.788119">
				<skin bone="warrior  R UpperArm" weight="0.333333"/>
				<skin bone="warrior  R Forearm" weight="0.666667"/>
			</vertex>
			<vertex x="-1.165" y="-0.209221" z="1.58366" r="1" g="1" b="1" a="1" nx="-0.540195" ny="-0.718767" nz="0.437681" u="0.0842617" v="0.805016">
				<skin bone="warrior  R Hand" weight="1"/>
			</vertex>
			<vertex x="-1.12521" y="0.096469" z="1.13584" r="1" g="1" b="1" a="1" nx="-0.513662" ny="0.256841" nz="-0.818648" u="0.0953926" v="0.757716">
				<skin bone="warrior  R Hand" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="-1.08174" y="0.0973019" z="1.59051" r="1" g="1" b="1" a="1" nx="-0.372874" ny="0.610718" nz="0.698562" u="0.101084" v="0.827908">
				<skin bone="warrior  R Hand" weight="1"/>
			</vertex>
			<vertex x="-1.165" y="-0.209221" z="1.58366" r="1" g="1" b="1" a="1" nx="-0.540195" ny="-0.718767" nz="0.437681" u="0.0842617" v="0.805016">
				<skin bone="warrior  R Hand" weight="1"/>
			</vertex>
			<vertex x="-0.536114" y="0.0926801" z="1.45096" r="1" g="1" b="1" a="1" nx="0.321336" ny="0.475185" nz="0.819111" u="0.148169" v="0.804616">
				<skin bone="warrior  R Forearm" weight="0.5"/>
				<skin bone="warrior  R UpperArm" weight="0.5"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="-0.536114" y="0.0926801" z="1.45096" r="1" g="1" b="1" a="1" nx="0.321336" ny="0.475185" nz="0.819111" u="0.148169" v="0.804616">
				<skin bone="warrior  R Forearm" weight="0.5"/>
				<skin bone="warrior  R UpperArm" weight="0.5"/>
			</vertex>
			<vertex x="-1.165" y="-0.209221" z="1.58366" r="1" g="1" b="1" a="1" nx="-0.540195" ny="-0.718767" nz="0.437681" u="0.0842617" v="0.805016">
				<skin bone="warrior  R Hand" weight="1"/>
			</vertex>
			<vertex x="-0.522976" y="-0.0337285" z="1.3499" r="1" g="1" b="1" a="1" nx="0.343071" ny="-0.933083" nz="-0.107975" u="0.14605" v="0.788119">
				<skin bone="warrior  R UpperArm" weight="0.333333"/>
				<skin bone="warrior  R Forearm" weight="0.666667"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="0.0934409" y="0.0160623" z="1.36687" r="1" g="1" b="1" a="1" nx="-0.996355" ny="-0.0770741" nz="0.0365643" u="0.359004" v="0.769581">
				<skin bone="warrior  Spine1" weight="0.5"/>
				<skin bone="warrior  Head" weight="0"/>
				<skin bone="warrior  L UpperArm" weight="0.5"/>
			</vertex>
			<vertex x="0.536114" y="0.0926801" z="1.45096" r="1" g="1" b="1" a="1" nx="-0.357816" ny="-0.118382" nz="0.926258" u="0.398038" v="0.781426">
				<skin bone="warrior  L UpperArm" weight="0.333333"/>
				<skin bone="warrior  L Forearm" weight="0.666667"/>
			</vertex>
			<vertex x="0.536114" y="0.0926801" z="1.24884" r="1" g="1" b="1" a="1" nx="-0.237192" ny="-0.247044" nz="-0.939526" u="0.389755" v="0.797635">
				<skin bone="warrior  L Forearm" weight="0.666667"/>
				<skin bone="warrior  L UpperArm" weight="0.333333"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="0.0934409" y="0.0160623" z="1.36687" r="1" g="1" b="1" a="1" nx="-0.996355" ny="-0.0770741" nz="0.0365643" u="0.359004" v="0.769581">
				<skin bone="warrior  Spine1" weight="0.5"/>
				<skin bone="warrior  Head" weight="0"/>
				<skin bone="warrior  L UpperArm" weight="0.5"/>
			</vertex>
			<vertex x="0.536114" y="0.0926801" z="1.24884" r="1" g="1" b="1" a="1" nx="-0.237192" ny="-0.247044" nz="-0.939526" u="0.398104" v="0.752701">
				<skin bone="warrior  L Forearm" weight="0.666667"/>
				<skin bone="warrior  L UpperArm" weight="0.333333"/>
			</vertex>
			<vertex x="0.549802" y="-0.0337285" z="1.3499" r="1" g="1" b="1" a="1" nx="-0.109018" ny="-0.993918" nz="-0.0155436" u="0.400323" v="0.767061">
				<skin bone="warrior  L UpperArm" weight="0.993833"/>
				<skin bone="warrior  L Forearm" weight="0.00616705"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="0.0934409" y="0.0160623" z="1.36687" r="1" g="1" b="1" a="1" nx="-0.996355" ny="-0.0770741" nz="0.0365643" u="0.359004" v="0.769581">
				<skin bone="warrior  Spine1" weight="0.5"/>
				<skin bone="warrior  Head" weight="0"/>
				<skin bone="warrior  L UpperArm" weight="0.5"/>
			</vertex>